// SPDX-License-Identifier: MIT
// Source: rev_scraping Phase 9e (MCP auth tools)
//
//! Two-phase MCP auth tools.
//!
//! MCP calls must not block for many minutes while a human completes an
//! interactive browser login. Therefore login is split into:
//!
//!   1. `auth_login_start`  — AUP-enforce, spawn the `rev-auth login` helper
//!      subprocess in headed mode, return an opaque `session_token`.
//!   2. `auth_login_complete` — poll for the helper to finish (or a marker
//!      file to appear), then read back ONLY `ProfileMeta` from the on-disk
//!      `AuthStore` and return that. Cookie values are NEVER materialized in
//!      MCP responses; this module never calls `AuthStore::load`.
//!
//! Plus two read-only tools:
//!
//!   * `auth_list`   — `ProfileMeta` summary, no values.
//!   * `auth_status` — freshness classification per profile.
//!
//! Delete is intentionally NOT exposed over MCP (CLI-only, requires TTY
//! confirmation per Phase 9d).

use std::path::{Path, PathBuf};
use std::process::Stdio;
use std::sync::Arc;
use std::time::{Duration, Instant};

use dashmap::DashMap;
use serde_json::{json, Value};
use stealth_agent_contracts::{ErrorEnvelope, ErrorKind};
use stealth_auth::auth_aup::{self, AuthAupDecision};
use stealth_auth::{storage, AuthStore, ProfileStatus};
use uuid::Uuid;

/// Default upper bound for how long `auth_login_complete` waits.
pub const DEFAULT_LOGIN_TIMEOUT_SECS: u64 = 600;

/// Lifetime of a `session_token` from issuance to consumption.
pub const SESSION_TTL_SECS: u64 = 600;

/// Set of in-process auth tool names. Used by the dispatcher to route to
/// [`handle_auth_tool`] before the subprocess argv translation path.
pub const AUTH_TOOLS: &[&str] = &[
    "auth_login_start",
    "auth_login_complete",
    "auth_list",
    "auth_status",
];

pub fn is_auth_tool(name: &str) -> bool {
    AUTH_TOOLS.contains(&name)
}

#[derive(Debug)]
pub enum AuthToolError {
    MissingField(&'static str),
    InvalidInput(String),
    AupRejected(String),
    SessionNotFound,
    SessionConsumed,
    LoginTimeout,
    LoginFailed(String),
    Store(String),
    Spawn(String),
}

impl AuthToolError {
    /// Map this in-process error onto the wire-format [`ErrorEnvelope`]
    /// (P4.3). Cookie values and other secrets are never included; only the
    /// pre-formatted `Display` message is propagated.
    pub fn to_envelope(&self) -> ErrorEnvelope {
        let msg = self.to_string();
        match self {
            AuthToolError::MissingField(_) | AuthToolError::InvalidInput(_) => {
                ErrorEnvelope::new(ErrorKind::Validation, msg)
            }
            AuthToolError::AupRejected(_) => ErrorEnvelope::new(ErrorKind::Aup, msg)
                .with_hint("verify authorized.toml entry for this domain"),
            AuthToolError::SessionNotFound => {
                ErrorEnvelope::new(ErrorKind::AuthSessionNotFound, msg)
                    .with_hint("re-run auth_login_start")
            }
            AuthToolError::SessionConsumed => {
                ErrorEnvelope::new(ErrorKind::AuthSessionNotFound, msg)
                    .with_hint("session_token is single-use; start a new login")
            }
            AuthToolError::LoginTimeout => ErrorEnvelope::new(ErrorKind::AuthSessionExpired, msg)
                .with_hint("user did not finish login in the allotted window")
                .retryable(Some(1_000)),
            AuthToolError::LoginFailed(_) => ErrorEnvelope::new(ErrorKind::Auth, msg),
            AuthToolError::Store(_) => ErrorEnvelope::new(ErrorKind::Internal, msg),
            AuthToolError::Spawn(_) => ErrorEnvelope::new(ErrorKind::BrowserNotFound, msg)
                .with_hint("ensure rev-auth helper is on PATH"),
        }
    }
}

impl std::fmt::Display for AuthToolError {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            AuthToolError::MissingField(k) => write!(f, "missing required argument: {k}"),
            AuthToolError::InvalidInput(m) => write!(f, "invalid input: {m}"),
            AuthToolError::AupRejected(m) => write!(f, "AUP rejected: {m}"),
            AuthToolError::SessionNotFound => write!(f, "session_token not found or expired"),
            AuthToolError::SessionConsumed => write!(f, "session_token already consumed"),
            AuthToolError::LoginTimeout => write!(f, "login_window_timeout"),
            AuthToolError::LoginFailed(m) => write!(f, "login helper failed: {m}"),
            AuthToolError::Store(m) => write!(f, "auth store error: {m}"),
            AuthToolError::Spawn(m) => write!(f, "spawn rev-auth failed: {m}"),
        }
    }
}

/// Registry of in-flight login sessions.
///
/// A `session_token` is a UUID v4 generated by `auth_login_start`. It is
/// consumed (single-use) by `auth_login_complete`. Each entry has a TTL of
/// [`SESSION_TTL_SECS`] enforced lazily on access.
#[derive(Default)]
pub struct AuthSessionRegistry {
    sessions: DashMap<String, AuthSession>,
}

#[derive(Debug, Clone)]
struct AuthSession {
    profile: String,
    domain: String,
    started_at: Instant,
    rev_auth_pid: u32,
    /// Set to `Consumed` once `auth_login_complete` finishes successfully.
    /// Not used as a state machine because we remove on completion.
    #[allow(dead_code)]
    completion_marker: PathBuf,
}

impl AuthSessionRegistry {
    pub fn new() -> Self {
        Self::default()
    }

    fn insert(&self, token: String, session: AuthSession) {
        self.sessions.insert(token, session);
    }

    fn take(&self, token: &str) -> Option<AuthSession> {
        // GC any expired tokens first so they cannot be replayed.
        self.gc();
        let entry = self.sessions.remove(token)?;
        Some(entry.1)
    }

    fn peek<F, R>(&self, token: &str, f: F) -> Option<R>
    where
        F: FnOnce(&AuthSession) -> R,
    {
        self.gc();
        self.sessions.get(token).map(|s| f(&s))
    }

    fn gc(&self) {
        let ttl = Duration::from_secs(SESSION_TTL_SECS);
        self.sessions.retain(|_, s| s.started_at.elapsed() < ttl);
    }

    /// For tests: insert a synthetic session entry.
    #[cfg(test)]
    pub fn insert_for_test(
        &self,
        token: &str,
        profile: &str,
        domain: &str,
        rev_auth_pid: u32,
        completion_marker: PathBuf,
    ) {
        self.insert(
            token.to_string(),
            AuthSession {
                profile: profile.to_string(),
                domain: domain.to_string(),
                started_at: Instant::now(),
                rev_auth_pid,
                completion_marker,
            },
        );
    }

    pub fn len(&self) -> usize {
        self.gc();
        self.sessions.len()
    }

    pub fn is_empty(&self) -> bool {
        self.len() == 0
    }
}

/// Configuration consumed by the auth-tool handlers.
#[derive(Clone, Debug)]
pub struct AuthToolConfig {
    /// Directory holding `<profile>.enc` and `<profile>.meta.json`.
    /// Defaults to `$XDG_CONFIG_HOME/rev_scraping/auth/`.
    pub auth_dir: PathBuf,
    /// Path to the `rev-auth` helper binary. When `None`, we look up via PATH.
    pub rev_auth_bin: Option<PathBuf>,
    /// Override the timeout for `auth_login_complete`. Production defaults
    /// to [`DEFAULT_LOGIN_TIMEOUT_SECS`]; tests may shrink this to milliseconds.
    pub login_timeout: Duration,
    /// Directory under which session completion-marker files live. Defaults
    /// to the system temp dir. The marker file is `rev-auth-<token>.complete`.
    pub marker_dir: PathBuf,
    /// When `true`, `auth_login_start` does NOT actually spawn rev-auth.
    /// Used by unit tests to drive registry state directly without launching
    /// a browser.
    pub dry_run: bool,
}

impl AuthToolConfig {
    pub fn defaults() -> Self {
        let auth_dir = dirs::config_dir()
            .map(|c| c.join("rev_scraping").join("auth"))
            .unwrap_or_else(|| PathBuf::from(".rev_scraping/auth"));
        Self {
            auth_dir,
            rev_auth_bin: None,
            login_timeout: Duration::from_secs(DEFAULT_LOGIN_TIMEOUT_SECS),
            marker_dir: std::env::temp_dir(),
            dry_run: false,
        }
    }
}

impl Default for AuthToolConfig {
    fn default() -> Self {
        Self::defaults()
    }
}

/// Combined dispatch for the four 9e tools.
pub fn handle_auth_tool(
    name: &str,
    args: &Value,
    registry: &Arc<AuthSessionRegistry>,
    cfg: &AuthToolConfig,
) -> Result<Value, AuthToolError> {
    match name {
        "auth_login_start" => handle_auth_login_start(args, registry, cfg),
        "auth_login_complete" => handle_auth_login_complete(args, registry, cfg),
        "auth_list" => handle_auth_list(cfg),
        "auth_status" => handle_auth_status(args, cfg),
        _ => Err(AuthToolError::InvalidInput(format!("unknown tool: {name}"))),
    }
}

fn require_str<'a>(args: &'a Value, k: &'static str) -> Result<&'a str, AuthToolError> {
    args.get(k)
        .and_then(|v| v.as_str())
        .filter(|s| !s.is_empty())
        .ok_or(AuthToolError::MissingField(k))
}

fn optional_str<'a>(args: &'a Value, k: &str) -> Option<&'a str> {
    args.get(k)
        .and_then(|v| v.as_str())
        .filter(|s| !s.is_empty())
}

/// Start a 2-phase login. Returns an opaque session token. Cookie values
/// are NEVER returned by this tool — only configuration that the caller
/// already supplied plus the spawned PID.
pub fn handle_auth_login_start(
    args: &Value,
    registry: &Arc<AuthSessionRegistry>,
    cfg: &AuthToolConfig,
) -> Result<Value, AuthToolError> {
    let profile = require_str(args, "profile")?.to_string();
    let url = require_str(args, "url")?.to_string();
    let domain = optional_str(args, "domain")
        .map(|s| s.to_string())
        .or_else(|| derive_domain_from_url(&url))
        .ok_or(AuthToolError::MissingField("domain"))?;
    let completion_pattern = optional_str(args, "completion_pattern").map(|s| s.to_string());

    if profile.contains('/') || profile.contains('\\') || profile == "." || profile == ".." {
        return Err(AuthToolError::InvalidInput(format!(
            "invalid profile name: {profile:?}"
        )));
    }

    match auth_aup::enforce(&domain, &url) {
        AuthAupDecision::Allowed => {}
        AuthAupDecision::Rejected { message } => {
            return Err(AuthToolError::AupRejected(message));
        }
    }

    let token = Uuid::new_v4().to_string();
    let marker = cfg.marker_dir.join(format!("rev-auth-{token}.complete"));

    // Best-effort: remove any stale marker from a previous run with the same
    // (now-recycled) UUID — astronomically unlikely but cheap to guard.
    let _ = std::fs::remove_file(&marker);

    let pid = if cfg.dry_run {
        0
    } else {
        spawn_rev_auth(
            cfg,
            &profile,
            &url,
            &domain,
            completion_pattern.as_deref(),
            &token,
        )?
    };

    registry.insert(
        token.clone(),
        AuthSession {
            profile: profile.clone(),
            domain: domain.clone(),
            started_at: Instant::now(),
            rev_auth_pid: pid,
            completion_marker: marker,
        },
    );

    Ok(json!({
        "ok": true,
        "session_token": token,
        "login_window_pid": pid,
        "profile": profile,
        "domain": domain,
        "hint": "Complete login in opened browser, then call auth_login_complete.",
        "cookie_values_returned": false,
    }))
}

fn derive_domain_from_url(url: &str) -> Option<String> {
    // Minimal scheme-stripping host extractor — avoids pulling in the `url`
    // crate just for this helper. `domain` is recommended to be passed
    // explicitly by callers; this is only a convenience fallback.
    let after_scheme = url.split_once("://").map(|(_, rest)| rest)?;
    let host_part = after_scheme.split(['/', '?', '#']).next()?;
    let host = host_part.split('@').next_back()?;
    let host = host.split(':').next()?;
    if host.is_empty() {
        None
    } else {
        Some(host.to_string())
    }
}

fn spawn_rev_auth(
    cfg: &AuthToolConfig,
    profile: &str,
    url: &str,
    domain: &str,
    completion_pattern: Option<&str>,
    session_token: &str,
) -> Result<u32, AuthToolError> {
    let bin = match &cfg.rev_auth_bin {
        Some(p) => p.clone(),
        None => which::which("rev-auth")
            .map_err(|e| AuthToolError::Spawn(format!("rev-auth not on PATH: {e}")))?,
    };
    let mut cmd = std::process::Command::new(&bin);
    cmd.arg("login")
        .arg("--profile")
        .arg(profile)
        .arg("--url")
        .arg(url)
        .arg("--domain")
        .arg(domain)
        // session token plumbed to the helper so it writes the completion
        // marker at the expected location. Helper accepts this as a
        // best-effort hint; older versions ignore it.
        .arg("--mcp-session-token")
        .arg(session_token)
        // We never read the helper's stdin from MCP — it's headed and
        // interactive with the user via the spawned browser window.
        .stdin(Stdio::null())
        .stdout(Stdio::null())
        .stderr(Stdio::null());
    if let Some(pat) = completion_pattern {
        cmd.arg("--completion-pattern").arg(pat);
    }
    let child = cmd
        .spawn()
        .map_err(|e| AuthToolError::Spawn(e.to_string()))?;
    Ok(child.id())
}

/// Poll for the marker file produced by `rev-auth` (or for the child PID to
/// exit and the AuthStore to contain the profile). On success, return
/// `ProfileMeta` ONLY — never cookie values.
pub fn handle_auth_login_complete(
    args: &Value,
    registry: &Arc<AuthSessionRegistry>,
    cfg: &AuthToolConfig,
) -> Result<Value, AuthToolError> {
    let token = require_str(args, "session_token")?.to_string();

    // Peek first to confirm the token is real; final removal happens after
    // either success or definitive failure so callers cannot accidentally
    // poll the same token from two MCP clients.
    let snapshot = registry
        .peek(&token, |s| s.clone())
        .ok_or(AuthToolError::SessionNotFound)?;

    let deadline = Instant::now() + cfg.login_timeout;
    let poll = Duration::from_millis(200);
    loop {
        if snapshot.completion_marker.exists() {
            break;
        }
        if !cfg.dry_run && snapshot.rev_auth_pid != 0 && !pid_alive(snapshot.rev_auth_pid) {
            // Helper exited without writing the marker — could be either
            // (a) success on an older rev-auth that has no marker support,
            //     in which case the AuthStore should contain the profile; or
            // (b) outright failure. We disambiguate by checking the store.
            if profile_present(&cfg.auth_dir, &snapshot.profile) {
                break;
            }
            // Definitive failure — consume the token so it cannot be reused.
            registry.take(&token);
            return Err(AuthToolError::LoginFailed(
                "rev-auth exited without saving a profile".to_string(),
            ));
        }
        if Instant::now() >= deadline {
            registry.take(&token);
            return Err(AuthToolError::LoginTimeout);
        }
        std::thread::sleep(poll);
    }

    // Consume the token (single-use).
    let _ = registry.take(&token);
    // Best-effort marker cleanup.
    let _ = std::fs::remove_file(&snapshot.completion_marker);

    // Read ProfileMeta only — we do NOT call AuthStore::load (which would
    // decrypt cookie values). list_profiles() returns sha256 prefixes only.
    let store = AuthStore::open(&cfg.auth_dir).map_err(|e| AuthToolError::Store(e.to_string()))?;
    let profiles = store
        .list_profiles()
        .map_err(|e| AuthToolError::Store(e.to_string()))?;
    let meta = profiles
        .into_iter()
        .find(|p| p.profile == snapshot.profile)
        .ok_or_else(|| AuthToolError::LoginFailed("profile not found after login".into()))?;

    Ok(json!({
        "ok": true,
        "profile": meta.profile,
        "domain": snapshot.domain,
        "cookie_count": meta.cookie_name_sha256_prefixes.len(),
        "saved_to": storage::enc_path(&cfg.auth_dir, &meta.profile)
            .display()
            .to_string(),
        "cookie_values_returned": false,
    }))
}

#[cfg(unix)]
fn pid_alive(pid: u32) -> bool {
    // Sending signal 0 probes whether the PID exists and we have permission.
    // We invoke `kill -0` via libc-less std for forbid(unsafe_code) safety.
    // For our purposes, falling through to /proc check on Linux is also fine,
    // but the most portable safe-Rust route is invoking `kill` as a process.
    // Spawning a process per 200ms poll is acceptable here; this only runs
    // during interactive login and the timeout is bounded.
    std::process::Command::new("kill")
        .arg("-0")
        .arg(pid.to_string())
        .stdout(Stdio::null())
        .stderr(Stdio::null())
        .status()
        .map(|s| s.success())
        .unwrap_or(false)
}

#[cfg(not(unix))]
fn pid_alive(_pid: u32) -> bool {
    // Windows: best-effort, treat as alive. The deadline still bounds us.
    true
}

fn profile_present(auth_dir: &Path, profile: &str) -> bool {
    storage::enc_path(auth_dir, profile).exists() && storage::meta_path(auth_dir, profile).exists()
}

pub fn handle_auth_list(cfg: &AuthToolConfig) -> Result<Value, AuthToolError> {
    // If the auth_dir does not exist yet, return an empty list rather than
    // attempting to create it from the MCP layer.
    if !cfg.auth_dir.exists() {
        return Ok(json!({
            "profiles": [],
            "total": 0,
            "cookie_values_returned": false,
        }));
    }
    let store = AuthStore::open(&cfg.auth_dir).map_err(|e| AuthToolError::Store(e.to_string()))?;
    let profiles = store
        .list_profiles()
        .map_err(|e| AuthToolError::Store(e.to_string()))?;
    let items: Vec<Value> = profiles
        .iter()
        .map(|m| {
            let status = store.status(&m.profile);
            json!({
                "profile": m.profile,
                "domains": m.domains,
                "created_at": m.created_at.to_rfc3339(),
                "last_used": m.last_used.to_rfc3339(),
                "cookie_count": m.cookie_name_sha256_prefixes.len(),
                "status": status_str(status),
            })
        })
        .collect();
    let total = items.len();
    Ok(json!({
        "profiles": items,
        "total": total,
        "cookie_values_returned": false,
    }))
}

pub fn handle_auth_status(args: &Value, cfg: &AuthToolConfig) -> Result<Value, AuthToolError> {
    let profile = require_str(args, "profile")?.to_string();
    if !cfg.auth_dir.exists() {
        // Always emit `cookie_values_returned:false` so the contract marker is
        // uniform across all branches (matches docs/json-schemas/auth_status.output.json).
        return Ok(json!({
            "profile": profile,
            "status": "Missing",
            "cookie_values_returned": false,
        }));
    }
    let store = AuthStore::open(&cfg.auth_dir).map_err(|e| AuthToolError::Store(e.to_string()))?;
    let status = store.status(&profile);
    Ok(json!({
        "profile": profile,
        "status": status_str(status),
        "cookie_values_returned": false,
    }))
}

fn status_str(s: ProfileStatus) -> &'static str {
    match s {
        ProfileStatus::Valid => "Valid",
        ProfileStatus::ExpiringSoon => "ExpiringSoon",
        ProfileStatus::ExpiringCritical => "ExpiringCritical",
        ProfileStatus::PartiallyExpired => "PartiallyExpired",
        ProfileStatus::AllExpired => "AllExpired",
        ProfileStatus::Missing => "Missing",
    }
}

#[cfg(test)]
pub(crate) mod tests {
    use super::*;
    use secrecy::SecretString;
    use stealth_auth::{Cookie, SameSite};
    use tempfile::TempDir;

    fn test_cfg(auth_dir: PathBuf, marker_dir: PathBuf, timeout: Duration) -> AuthToolConfig {
        AuthToolConfig {
            auth_dir,
            rev_auth_bin: None,
            login_timeout: timeout,
            marker_dir,
            dry_run: true,
        }
    }

    fn seed_profile(auth_dir: &Path, profile: &str, domain: &str) {
        let store = AuthStore::open_with_passphrase(
            auth_dir,
            SecretString::from("test passphrase".to_string()),
        )
        .unwrap();
        let cookie = Cookie {
            name: "sid".to_string(),
            value: SecretString::from("SUPER_SECRET_VALUE_PHASE9E".to_string()),
            domain: domain.to_string(),
            path: "/".to_string(),
            expires: None,
            secure: true,
            http_only: true,
            same_site: SameSite::Lax,
        };
        store.save(profile, &[cookie], "").unwrap();
    }

    fn write_aup_allowlist(dir: &Path, domain_re: &str, allowed: bool) {
        // Synthesize an authorized.toml at $HOME/.rev_scraping/authorized.toml
        // by temporarily redirecting HOME for the test process. The caller
        // sets HOME = dir before invoking AUP-affected paths.
        let aup_dir = dir.join(".rev_scraping");
        std::fs::create_dir_all(&aup_dir).unwrap();
        // Use TOML literal strings (single quotes) to avoid having to escape
        // regex backslashes in the URL pattern.
        let body = format!(
            "[[targets]]\nurl_pattern = '{}'\nauth_allowed = {}\n",
            domain_re, allowed
        );
        std::fs::write(aup_dir.join("authorized.toml"), body).unwrap();
    }

    pub(crate) fn env_test_lock() -> &'static std::sync::Mutex<()> {
        static LOCK: std::sync::OnceLock<std::sync::Mutex<()>> = std::sync::OnceLock::new();
        LOCK.get_or_init(|| std::sync::Mutex::new(()))
    }

    struct EnvVarGuard {
        name: &'static str,
        old_value: Option<std::ffi::OsString>,
    }

    impl EnvVarGuard {
        fn set(name: &'static str, value: impl AsRef<std::ffi::OsStr>) -> Self {
            let old_value = std::env::var_os(name);
            std::env::set_var(name, value);
            Self { name, old_value }
        }
    }

    impl Drop for EnvVarGuard {
        fn drop(&mut self) {
            if let Some(value) = self.old_value.as_ref() {
                std::env::set_var(self.name, value);
            } else {
                std::env::remove_var(self.name);
            }
        }
    }

    #[test]
    fn is_auth_tool_recognizes_all_four() {
        assert!(is_auth_tool("auth_login_start"));
        assert!(is_auth_tool("auth_login_complete"));
        assert!(is_auth_tool("auth_list"));
        assert!(is_auth_tool("auth_status"));
        assert!(!is_auth_tool("spider"));
        assert!(!is_auth_tool("recipe_list"));
    }

    #[test]
    fn auth_login_start_returns_session_token_when_aup_allows() {
        let _lock = env_test_lock().lock().unwrap();
        let home = TempDir::new().unwrap();
        let _home_guard = EnvVarGuard::set("HOME", home.path());
        write_aup_allowlist(home.path(), r"^https://login\.example\.com/", true);

        let auth_dir = TempDir::new().unwrap();
        let marker = TempDir::new().unwrap();
        let cfg = test_cfg(
            auth_dir.path().to_path_buf(),
            marker.path().to_path_buf(),
            Duration::from_secs(1),
        );
        let reg = Arc::new(AuthSessionRegistry::new());
        let args = json!({
            "profile": "work",
            "url": "https://login.example.com/",
            "domain": "example.com",
        });
        let v = handle_auth_login_start(&args, &reg, &cfg).unwrap();
        assert_eq!(v["ok"], true);
        let tok = v["session_token"].as_str().unwrap();
        assert_eq!(tok.len(), 36); // UUID
        assert_eq!(v["cookie_values_returned"], false);
        assert!(!reg.is_empty());
    }

    #[test]
    fn auth_login_start_rejects_unauthorized_domain() {
        let _lock = env_test_lock().lock().unwrap();
        let home = TempDir::new().unwrap();
        let _home_guard = EnvVarGuard::set("HOME", home.path());
        // Only allow example.com; we'll try evil.com.
        write_aup_allowlist(home.path(), r"^https://login\.example\.com/", true);

        let auth_dir = TempDir::new().unwrap();
        let marker = TempDir::new().unwrap();
        let cfg = test_cfg(
            auth_dir.path().to_path_buf(),
            marker.path().to_path_buf(),
            Duration::from_secs(1),
        );
        let reg = Arc::new(AuthSessionRegistry::new());
        let args = json!({
            "profile": "evil",
            "url": "https://login.evil.com/",
            "domain": "evil.com",
        });
        let err = handle_auth_login_start(&args, &reg, &cfg).unwrap_err();
        assert!(matches!(err, AuthToolError::AupRejected(_)));
        assert!(reg.is_empty());
    }

    #[test]
    fn auth_login_complete_waits_for_completion_marker_then_returns_meta() {
        let _lock = env_test_lock().lock().unwrap();
        let home = TempDir::new().unwrap();
        let _home_guard = EnvVarGuard::set("HOME", home.path());
        write_aup_allowlist(home.path(), r"^https://login\.example\.com/", true);

        let auth_dir = TempDir::new().unwrap();
        let marker = TempDir::new().unwrap();

        // Pre-seed the profile so list_profiles() finds it after the marker.
        seed_profile(auth_dir.path(), "work", "example.com");

        let cfg = test_cfg(
            auth_dir.path().to_path_buf(),
            marker.path().to_path_buf(),
            Duration::from_secs(5),
        );
        let reg = Arc::new(AuthSessionRegistry::new());

        let start = handle_auth_login_start(
            &json!({
                "profile": "work",
                "url": "https://login.example.com/",
                "domain": "example.com",
            }),
            &reg,
            &cfg,
        )
        .unwrap();
        let tok = start["session_token"].as_str().unwrap().to_string();

        // Simulate rev-auth completing by touching the marker file.
        let marker_path = marker.path().join(format!("rev-auth-{tok}.complete"));
        std::thread::spawn(move || {
            std::thread::sleep(Duration::from_millis(150));
            std::fs::write(&marker_path, b"done").unwrap();
        });

        let v = handle_auth_login_complete(&json!({ "session_token": tok }), &reg, &cfg).unwrap();
        assert_eq!(v["ok"], true);
        assert_eq!(v["profile"], "work");
        assert_eq!(v["cookie_values_returned"], false);
        // Token should be consumed.
        assert!(reg.is_empty());
    }

    #[test]
    fn auth_login_complete_timeout_returns_error() {
        let auth_dir = TempDir::new().unwrap();
        let marker = TempDir::new().unwrap();
        let cfg = test_cfg(
            auth_dir.path().to_path_buf(),
            marker.path().to_path_buf(),
            Duration::from_millis(150),
        );
        let reg = Arc::new(AuthSessionRegistry::new());
        let token = "00000000-0000-4000-8000-000000000001";
        reg.insert_for_test(
            token,
            "stuck",
            "example.com",
            0,
            marker.path().join(format!("rev-auth-{token}.complete")),
        );
        let err =
            handle_auth_login_complete(&json!({ "session_token": token }), &reg, &cfg).unwrap_err();
        assert!(matches!(err, AuthToolError::LoginTimeout));
        // Token consumed even on timeout so it can't be replayed.
        assert!(reg.is_empty());
    }

    #[test]
    fn auth_login_complete_unknown_session_token_errors() {
        let cfg = test_cfg(
            TempDir::new().unwrap().path().to_path_buf(),
            TempDir::new().unwrap().path().to_path_buf(),
            Duration::from_millis(50),
        );
        let reg = Arc::new(AuthSessionRegistry::new());
        let err = handle_auth_login_complete(
            &json!({ "session_token": "11111111-2222-3333-4444-555555555555" }),
            &reg,
            &cfg,
        )
        .unwrap_err();
        assert!(matches!(err, AuthToolError::SessionNotFound));
    }

    #[test]
    fn auth_list_via_mcp_redacts_values() {
        let auth_dir = TempDir::new().unwrap();
        seed_profile(auth_dir.path(), "alpha", "example.com");
        seed_profile(auth_dir.path(), "beta", "another.com");
        let cfg = test_cfg(
            auth_dir.path().to_path_buf(),
            TempDir::new().unwrap().path().to_path_buf(),
            Duration::from_secs(1),
        );
        let v = handle_auth_list(&cfg).unwrap();
        let s = serde_json::to_string(&v).unwrap();
        assert!(!s.contains("SUPER_SECRET_VALUE_PHASE9E"));
        assert_eq!(v["total"], 2);
        assert_eq!(v["cookie_values_returned"], false);
    }

    #[test]
    fn auth_status_returns_classification_valid() {
        let auth_dir = TempDir::new().unwrap();
        seed_profile(auth_dir.path(), "alpha", "example.com");
        let cfg = test_cfg(
            auth_dir.path().to_path_buf(),
            TempDir::new().unwrap().path().to_path_buf(),
            Duration::from_secs(1),
        );
        let v = handle_auth_status(&json!({ "profile": "alpha" }), &cfg).unwrap();
        assert_eq!(v["status"], "Valid");
        let v2 = handle_auth_status(&json!({ "profile": "nope" }), &cfg).unwrap();
        assert_eq!(v2["status"], "Missing");
    }

    #[test]
    fn cookie_values_never_appear_in_mcp_response() {
        let _lock = env_test_lock().lock().unwrap();
        // Invariant: across all auth-tool responses, the secret cookie value
        // string must not appear.
        let home = TempDir::new().unwrap();
        let _home_guard = EnvVarGuard::set("HOME", home.path());
        write_aup_allowlist(home.path(), r"^https://login\.example\.com/", true);

        let auth_dir = TempDir::new().unwrap();
        let marker = TempDir::new().unwrap();
        seed_profile(auth_dir.path(), "work", "example.com");

        let cfg = test_cfg(
            auth_dir.path().to_path_buf(),
            marker.path().to_path_buf(),
            Duration::from_secs(2),
        );
        let reg = Arc::new(AuthSessionRegistry::new());
        const SECRET: &str = "SUPER_SECRET_VALUE_PHASE9E";

        let v_start = handle_auth_login_start(
            &json!({
                "profile": "work",
                "url": "https://login.example.com/",
                "domain": "example.com",
            }),
            &reg,
            &cfg,
        )
        .unwrap();
        let tok = v_start["session_token"].as_str().unwrap().to_string();
        let marker_path = marker.path().join(format!("rev-auth-{tok}.complete"));
        std::fs::write(&marker_path, b"done").unwrap();
        let v_done =
            handle_auth_login_complete(&json!({ "session_token": tok }), &reg, &cfg).unwrap();
        let v_list = handle_auth_list(&cfg).unwrap();
        let v_status = handle_auth_status(&json!({ "profile": "work" }), &cfg).unwrap();

        for v in [&v_start, &v_done, &v_list, &v_status] {
            let s = serde_json::to_string(v).unwrap();
            assert!(!s.contains(SECRET), "secret leaked in: {s}");
            assert!(!s.to_lowercase().contains("password"));
        }
    }

    #[test]
    fn invalid_profile_name_rejected_at_start() {
        let cfg = test_cfg(
            TempDir::new().unwrap().path().to_path_buf(),
            TempDir::new().unwrap().path().to_path_buf(),
            Duration::from_secs(1),
        );
        let reg = Arc::new(AuthSessionRegistry::new());
        let err = handle_auth_login_start(
            &json!({
                "profile": "../escape",
                "url": "https://login.example.com/",
                "domain": "example.com",
            }),
            &reg,
            &cfg,
        )
        .unwrap_err();
        assert!(matches!(err, AuthToolError::InvalidInput(_)));
    }
}
