// SPDX-License-Identifier: MIT
// Source: rev_scraping Lane E P8 (new module, original work)
//
//! Deterministic renderer for `docs/MCP_REFERENCE.md`.
//!
//! This module is the single source of truth for the markdown layout of the
//! MCP reference document. Both the `gen_reference` binary and the
//! `mcp_reference_freshness` regression test call into [`render_reference`]
//! and never reformat the output downstream — so the CI freshness gate is a
//! pure byte comparison against the committed file.
//!
//! Determinism contract:
//!   * `tool_definitions()` returns tools in a fixed `Vec` order (declared
//!     order in [`crate::tools`]).
//!   * Per-tool `properties` are sorted alphabetically via [`BTreeMap`] so
//!     we do not depend on `serde_json::Map`'s insertion-preserving (but
//!     not lexicographically sorted) iteration order.
//!   * Required-field arrays are emitted in their declared order, which
//!     matches the JSON-Schema `required` array.
//!   * The 26 `ErrorKind` rows come from
//!     [`stealth_agent_contracts::all_error_kind_docs`] which fixes the
//!     P1-then-P4.3 canonical order at the source.

use std::collections::BTreeMap;

use serde_json::Value;
use stealth_agent_contracts::all_error_kind_docs;

use crate::{tool_definitions, MCP_PROTOCOL_VERSION, SERVER_NAME};

/// Path under `docs/json-schemas/` where each tool's outputSchema lives.
/// Used to build relative links in the per-tool section.
const OUTPUT_SCHEMA_DIR_REL: &str = "docs/json-schemas";

/// Render the full `docs/MCP_REFERENCE.md` content as a UTF-8 `String`.
///
/// The output is byte-stable across runs on the same workspace: calling
/// this function twice always returns the exact same bytes. Drift between
/// the committed file and a fresh render is treated as a CI failure.
pub fn render_reference() -> String {
    let mut out = String::with_capacity(32 * 1024);
    write_header(&mut out);
    write_envelope_section(&mut out);
    write_tools_overview(&mut out);
    write_tool_details(&mut out);
    write_error_kind_table(&mut out);
    write_runtime_invariants(&mut out);
    out
}

fn write_header(out: &mut String) {
    out.push_str("# stealth-mcp Reference\n\n");
    out.push_str(
        "Auto-generated by `cargo run -p stealth-mcp --bin gen_reference`. \
         Do **not** edit this file by hand — your edits will be overwritten \
         on the next regeneration. The freshness regression test \
         `mcp_reference_freshness` (run as part of `cargo test --workspace`) \
         fails if this file drifts from the in-tree sources, so any tool or \
         schema change must be accompanied by a regenerated reference.\n\n",
    );
    out.push_str(
        "Source of truth:\n\n\
         - 16 tool definitions: [`crates/stealth-mcp/src/tools.rs`](../crates/stealth-mcp/src/tools.rs)\n\
         - Output schemas: [`docs/json-schemas/*.output.json`](./json-schemas/)\n\
         - 26 `ErrorKind` variants: [`crates/stealth-agent-contracts/src/error.rs`](../crates/stealth-agent-contracts/src/error.rs)\n\n",
    );
}

fn write_envelope_section(out: &mut String) {
    out.push_str("## 1. JSON-RPC 2.0 transport\n\n");
    out.push_str(
        "`stealth-mcp` speaks line-delimited JSON-RPC 2.0 over `stdin` / `stdout`. \
         Each request is a single JSON object on one line; each response is a \
         single JSON object on one line. Blank lines are tolerated as keepalives.\n\n",
    );
    out.push_str("Supported methods:\n\n");
    out.push_str("| Method | Purpose |\n|---|---|\n");
    out.push_str(
        "| `initialize` | Client/server handshake; returns server name, version, protocol. |\n",
    );
    out.push_str("| `notifications/initialized` | Client-side notification; no response. |\n");
    out.push_str(
        "| `tools/list` | Enumerate all 16 tools with their inputSchema and outputSchema. |\n",
    );
    out.push_str(
        "| `tools/call` | Dispatch a tool by name; arguments validated against inputSchema. |\n\n",
    );

    out.push_str("Response envelope on success:\n\n");
    out.push_str("```json\n");
    out.push_str("{\n  \"jsonrpc\": \"2.0\",\n  \"id\": <RpcId>,\n  \"result\": { ... }\n}\n");
    out.push_str("```\n\n");

    out.push_str("Tool-level failures are returned inside `result.structuredContent.error` as an `ErrorEnvelope` (see §3). JSON-RPC `error` is reserved for transport-level failures (parse error, method not found, invalid params).\n\n");

    out.push_str("Server identity:\n\n");
    out.push_str(&format!("- `serverInfo.name`: `{SERVER_NAME}`\n"));
    out.push_str(
        "- `serverInfo.version`: workspace `Cargo.toml` package version (`CARGO_PKG_VERSION`).\n",
    );
    out.push_str(&format!(
        "- `protocolVersion`: `{MCP_PROTOCOL_VERSION}`\n\n"
    ));
}

fn write_tools_overview(out: &mut String) {
    out.push_str("## 2. Tools\n\n");
    out.push_str("### 2.1 Overview (16 tools)\n\n");
    out.push_str("| # | Name | Description |\n|---|---|---|\n");
    for (idx, t) in tool_definitions().iter().enumerate() {
        out.push_str(&format!(
            "| {} | [`{}`](#tool-{}) | {} |\n",
            idx + 1,
            t.name,
            anchor(t.name),
            escape_md_cell(t.description)
        ));
    }
    out.push('\n');
}

fn write_tool_details(out: &mut String) {
    out.push_str("### 2.2 Per-tool detail\n\n");
    for t in tool_definitions() {
        out.push_str(&format!(
            "<a id=\"tool-{anchor}\"></a>\n#### `{name}`\n\n",
            anchor = anchor(t.name),
            name = t.name,
        ));
        out.push_str(&format!("{}\n\n", t.description));

        let (required, properties) = extract_schema_fields(&t.input_schema);

        out.push_str("**Required arguments:**\n\n");
        if required.is_empty() {
            out.push_str("_None._\n\n");
        } else {
            out.push_str("| Field | Type | Description |\n|---|---|---|\n");
            for name in &required {
                if let Some(schema) = properties.get(name.as_str()) {
                    out.push_str(&format!(
                        "| `{}` | {} | {} |\n",
                        name,
                        type_label(schema),
                        escape_md_cell(field_description(schema))
                    ));
                }
            }
            out.push('\n');
        }

        let optional: Vec<&String> = properties
            .keys()
            .filter(|k| !required.iter().any(|r| r == *k))
            .collect();
        out.push_str("**Optional arguments:**\n\n");
        if optional.is_empty() {
            out.push_str("_None._\n\n");
        } else {
            out.push_str("| Field | Type | Description | Default |\n|---|---|---|---|\n");
            for name in optional {
                let schema = &properties[name.as_str()];
                let default_repr = schema
                    .get("default")
                    .map(|v| format!("`{}`", compact_json(v)))
                    .unwrap_or_else(|| "—".to_string());
                out.push_str(&format!(
                    "| `{}` | {} | {} | {} |\n",
                    name,
                    type_label(schema),
                    escape_md_cell(field_description(schema)),
                    default_repr
                ));
            }
            out.push('\n');
        }

        out.push_str("**Example `tools/call` request:**\n\n");
        out.push_str("```json\n");
        out.push_str(&example_request_json(t.name, &required, &properties));
        out.push_str("\n```\n\n");

        out.push_str(&format!(
            "**Output schema:** [`{dir}/{file}.output.json`](./json-schemas/{file}.output.json)\n\n",
            dir = OUTPUT_SCHEMA_DIR_REL,
            file = t.name,
        ));

        let mut output_props: Vec<(&str, &Value)> = t
            .output_schema
            .get("properties")
            .and_then(|v| v.as_object())
            .map(|m| m.iter().map(|(k, v)| (k.as_str(), v)).collect())
            .unwrap_or_default();
        output_props.sort_by_key(|(k, _)| *k);
        if !output_props.is_empty() {
            out.push_str("**Top-level response fields:**\n\n");
            out.push_str("| Field | Type | Description |\n|---|---|---|\n");
            for (name, schema) in output_props {
                out.push_str(&format!(
                    "| `{}` | {} | {} |\n",
                    name,
                    type_label(schema),
                    escape_md_cell(field_description(schema))
                ));
            }
            out.push('\n');
        }
    }
}

fn write_error_kind_table(out: &mut String) {
    out.push_str("## 3. ErrorEnvelope and ErrorKind\n\n");
    out.push_str(
        "Every tool failure surfaces as an `ErrorEnvelope` carried under \
         `result.structuredContent.error` on the JSON-RPC response. The \
         envelope is a closed contract — exactly **26** `ErrorKind` variants \
         are emitted across the stealth-* boundary, and the set never grows \
         without a deliberate breaking change.\n\n",
    );
    out.push_str("Envelope shape:\n\n");
    out.push_str("```json\n");
    out.push_str(
        "{\n  \"kind\": \"<snake_case ErrorKind>\",\n  \"message\": \"<safe-to-log human text>\",\n  \"retryable\": false,\n  \"hint\": \"<optional operator hint>\",\n  \"retry_after_ms\": null\n}\n",
    );
    out.push_str("```\n\n");

    out.push_str("### 3.1 26 ErrorKind variants\n\n");
    out.push_str("| # | Wire name | When emitted | Retriable | Hint |\n|---|---|---|---|---|\n");
    for (idx, (_, doc)) in all_error_kind_docs().iter().enumerate() {
        out.push_str(&format!(
            "| {} | `{}` | {} | {} | {} |\n",
            idx + 1,
            doc.wire_name,
            escape_md_cell(doc.when_emitted),
            if doc.retriable { "yes" } else { "no" },
            escape_md_cell(doc.hint),
        ));
    }
    out.push('\n');
}

fn write_runtime_invariants(out: &mut String) {
    out.push_str("## 4. Runtime invariants\n\n");
    out.push_str("### 4.1 Rate limit\n\n");
    out.push_str(
        "Per-host QPS is enforced inside `stealth-cli`. When the limit is \
         exceeded, the tool returns `kind=\"rate_limit\"` with a populated \
         `retry_after_ms`. Callers MUST honor the hint before retrying; \
         retrying earlier is itself a rate-limit violation.\n\n",
    );
    out.push_str("### 4.2 Idempotency\n\n");
    out.push_str(
        "`spider`, `relocate`, and `cf_evaluate` are idempotent given the \
         same `session_id` + arguments — repeated calls return the same \
         `session_id` and converge on the same recipe. `auth_login_*` \
         session tokens are **single-use**: calling `auth_login_complete` a \
         second time with the same token returns `kind=\"auth_session_not_found\"`.\n\n",
    );
    out.push_str("### 4.3 Sessions\n\n");
    out.push_str(
        "`session_id` is a UUIDv4 issued by `spider` (or supplied by the \
         caller) and persisted with VPN binding + recipe hits + optional \
         auth profile reference. `session_show` returns this metadata — \
         cookie values and other secrets are **never** disclosed by any \
         tool, including `auth_*`.\n\n",
    );
    out.push_str("### 4.4 AUP and SSRF\n\n");
    out.push_str(
        "Every URL-bearing tool validates the target against the AUP \
         allowlist (`policy.toml`) and the SSRF guard (private/internal \
         ranges blocked). Violations surface as `kind=\"aup\"` or \
         `kind=\"ssrf\"` and are non-retriable.\n\n",
    );
}

// -----------------------------------------------------------------------
// Helpers
// -----------------------------------------------------------------------

fn anchor(name: &str) -> String {
    name.replace('_', "-")
}

fn extract_schema_fields(schema: &Value) -> (Vec<String>, BTreeMap<String, Value>) {
    let required: Vec<String> = schema
        .get("required")
        .and_then(|v| v.as_array())
        .map(|a| {
            a.iter()
                .filter_map(|v| v.as_str().map(|s| s.to_string()))
                .collect()
        })
        .unwrap_or_default();

    let properties: BTreeMap<String, Value> = schema
        .get("properties")
        .and_then(|v| v.as_object())
        .map(|m| m.iter().map(|(k, v)| (k.clone(), v.clone())).collect())
        .unwrap_or_default();

    (required, properties)
}

fn field_description(schema: &Value) -> &str {
    schema
        .get("description")
        .and_then(|v| v.as_str())
        .unwrap_or("")
}

fn type_label(schema: &Value) -> String {
    if let Some(arr) = schema.get("enum").and_then(|v| v.as_array()) {
        let items: Vec<String> = arr
            .iter()
            .filter_map(|v| v.as_str().map(|s| format!("`{s}`")))
            .collect();
        if !items.is_empty() {
            return format!("enum: {}", items.join(" \\| "));
        }
    }
    match schema.get("type") {
        Some(Value::String(s)) => format!("`{s}`"),
        Some(Value::Array(arr)) => {
            let parts: Vec<String> = arr
                .iter()
                .filter_map(|v| v.as_str().map(|s| format!("`{s}`")))
                .collect();
            if parts.is_empty() {
                "`unknown`".to_string()
            } else {
                parts.join(" \\| ")
            }
        }
        _ => "`unknown`".to_string(),
    }
}

fn compact_json(v: &Value) -> String {
    serde_json::to_string(v).unwrap_or_default()
}

fn example_request_json(
    tool: &str,
    required: &[String],
    properties: &BTreeMap<String, Value>,
) -> String {
    let mut args = serde_json::Map::new();
    for name in required {
        let schema = match properties.get(name) {
            Some(s) => s,
            None => continue,
        };
        let value = schema
            .get("examples")
            .and_then(|v| v.as_array())
            .and_then(|a| a.first())
            .cloned()
            .unwrap_or_else(|| placeholder_for(schema));
        args.insert(name.clone(), value);
    }
    let envelope = serde_json::json!({
        "jsonrpc": "2.0",
        "id": 1,
        "method": "tools/call",
        "params": {
            "name": tool,
            "arguments": Value::Object(args),
        }
    });
    serde_json::to_string_pretty(&envelope).unwrap_or_default()
}

fn placeholder_for(schema: &Value) -> Value {
    match schema.get("type").and_then(|v| v.as_str()) {
        Some("string") => Value::String("<value>".into()),
        Some("number") => serde_json::json!(0),
        Some("boolean") => Value::Bool(false),
        Some("object") => Value::Object(Default::default()),
        _ => Value::Null,
    }
}

fn escape_md_cell(s: &str) -> String {
    s.replace('|', "\\|").replace('\n', " ")
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn render_is_byte_stable_across_two_calls() {
        let a = render_reference();
        let b = render_reference();
        assert_eq!(a, b, "render_reference must be deterministic");
    }

    #[test]
    fn render_includes_all_16_tools() {
        let out = render_reference();
        for t in tool_definitions() {
            assert!(
                out.contains(&format!("#### `{}`", t.name)),
                "tool {} must appear as a detail heading",
                t.name
            );
        }
    }

    #[test]
    fn render_includes_all_26_error_kinds() {
        let out = render_reference();
        for (_, doc) in all_error_kind_docs() {
            assert!(
                out.contains(&format!("`{}`", doc.wire_name)),
                "ErrorKind {} must appear in the table",
                doc.wire_name
            );
        }
    }

    #[test]
    fn render_starts_with_header() {
        let out = render_reference();
        assert!(out.starts_with("# stealth-mcp Reference\n"));
    }
}
