// SPDX-License-Identifier: MIT
// Source: new crate for rev_scraping v1.0.0 (Phase 3 MCP server)
//
//! Tool registry and CLI argument translation.
//!
//! Each MCP tool maps 1:1 to a `rev-stealth` subcommand. We accept the tool
//! call arguments, validate the minimum required fields, then translate them
//! into a CLI argv vector. AUP enforcement, allowlist checks, and JSON
//! schema validation of outputs are left to the CLI itself (see
//! ExecPlan §3.4 / S12); this layer is a thin forwarder.

use serde_json::{json, Value};

/// A tool definition as advertised over `tools/list`.
#[derive(Debug, Clone)]
pub struct ToolDefinition {
    pub name: &'static str,
    pub description: &'static str,
    pub input_schema: Value,
}

impl ToolDefinition {
    pub fn to_json(&self) -> Value {
        json!({
            "name": self.name,
            "description": self.description,
            "inputSchema": self.input_schema,
        })
    }
}

/// Returns the full set of MCP tools exposed by this server.
pub fn tool_definitions() -> Vec<ToolDefinition> {
    vec![
        ToolDefinition {
            name: "spider",
            description:
                "Scrape a URL with stealth (obscura) + optional CF evaluation + adaptive relocate. AUP allowlist required.",
            input_schema: json!({
                "type": "object",
                "required": ["url"],
                "properties": {
                    "url": { "type": "string" },
                    "session_id": { "type": "string", "description": "UUID, autogenerated if omitted" },
                    "mobile_preset": {
                        "type": "string",
                        "enum": ["iphone15pro","iphone15promax","ipadprom4","pixel9pro","pixel8a","galaxys24ultra"]
                    },
                    "cf_evaluate": { "type": "boolean", "default": false },
                    "vpn": { "type": "boolean", "default": false },
                    "stable_id": { "type": "string" },
                    "threshold": { "type": "number", "default": 0.85 },
                    "strict": { "type": "boolean", "default": false }
                }
            }),
        },
        ToolDefinition {
            name: "relocate",
            description: "Adaptive relocate a previously recorded element via stealth-parse.",
            input_schema: json!({
                "type": "object",
                "required": ["session_id", "stable_id"],
                "properties": {
                    "session_id": { "type": "string" },
                    "stable_id": { "type": "string" },
                    "html": { "type": "string", "description": "Raw HTML to search in (alternative to url)" },
                    "url": { "type": "string" },
                    "threshold": { "type": "number", "default": 0.85 }
                }
            }),
        },
        ToolDefinition {
            name: "cf_evaluate",
            description: "Evaluate Cloudflare Turnstile resilience on an authorized target.",
            input_schema: json!({
                "type": "object",
                "required": ["url"],
                "properties": {
                    "url": { "type": "string" },
                    "session_id": { "type": "string" }
                }
            }),
        },
        ToolDefinition {
            name: "doctor",
            description: "Run leak-guard / vpn / captcha sidecar health diagnostics.",
            input_schema: json!({
                "type": "object",
                "properties": {
                    "container": { "type": "string", "default": "gluetun" },
                    "expected_country": { "type": "string" }
                }
            }),
        },
        ToolDefinition {
            name: "recipe_list",
            description: "List all site recipes stored in ~/.rev_scraping/sites/.",
            input_schema: json!({
                "type": "object",
                "properties": {}
            }),
        },
        ToolDefinition {
            name: "recipe_show",
            description: "Return the full SiteRecipe JSON for a given domain.",
            input_schema: json!({
                "type": "object",
                "required": ["domain"],
                "properties": {
                    "domain": { "type": "string" }
                }
            }),
        },
        ToolDefinition {
            name: "recipe_remove",
            description: "Remove a recipe file. Preview unless confirm=true.",
            input_schema: json!({
                "type": "object",
                "required": ["domain"],
                "properties": {
                    "domain": { "type": "string" },
                    "confirm": { "type": "boolean", "default": false }
                }
            }),
        },
        ToolDefinition {
            name: "recipe_propose_endpoint",
            description: "Append a new endpoint to an existing site recipe. Secret-leak rejected.",
            input_schema: json!({
                "type": "object",
                "required": ["domain", "endpoint"],
                "properties": {
                    "domain": { "type": "string" },
                    "endpoint": {
                        "type": "object",
                        "required": ["purpose", "path"],
                        "properties": {
                            "purpose": { "type": "string" },
                            "path": { "type": "string" },
                            "http_method": { "type": "string", "default": "GET" },
                            "url_pattern": { "type": "string" }
                        }
                    }
                }
            }),
        },
        ToolDefinition {
            name: "recipe_export",
            description: "Export all recipes as a base64-encoded JSON array.",
            input_schema: json!({
                "type": "object",
                "properties": {}
            }),
        },
        ToolDefinition {
            name: "recipe_import",
            description: "Import recipes from a base64-encoded JSON array. Secret-rejected and path-traversal guarded.",
            input_schema: json!({
                "type": "object",
                "required": ["payload"],
                "properties": {
                    "payload": { "type": "string", "description": "base64-encoded JSON array of SiteRecipe" }
                }
            }),
        },
        ToolDefinition {
            name: "auth_login_start",
            description: "Phase 1 of 2-phase login: AUP-enforce + spawn rev-auth helper. Returns a session_token. Cookie values are never returned.",
            input_schema: json!({
                "type": "object",
                "required": ["profile", "url"],
                "properties": {
                    "profile": { "type": "string" },
                    "url": { "type": "string" },
                    "domain": { "type": "string" },
                    "completion_pattern": { "type": "string" }
                }
            }),
        },
        ToolDefinition {
            name: "auth_login_complete",
            description: "Phase 2 of 2-phase login: poll until rev-auth finishes, then return ProfileMeta. Single-use session_token. Cookie values never returned.",
            input_schema: json!({
                "type": "object",
                "required": ["session_token"],
                "properties": {
                    "session_token": { "type": "string" }
                }
            }),
        },
        ToolDefinition {
            name: "auth_list",
            description: "List all stored auth profiles (ProfileMeta only, cookie values never disclosed).",
            input_schema: json!({
                "type": "object",
                "properties": {}
            }),
        },
        ToolDefinition {
            name: "auth_status",
            description: "Return freshness classification for an auth profile (Valid|PartiallyExpired|AllExpired|Missing).",
            input_schema: json!({
                "type": "object",
                "required": ["profile"],
                "properties": {
                    "profile": { "type": "string" }
                }
            }),
        },
        ToolDefinition {
            name: "vpn_rotate",
            description: "Rotate VPN exit (Surfshark via Gluetun).",
            input_schema: json!({
                "type": "object",
                "properties": {
                    "provider": { "type": "string", "default": "surfshark" },
                    "strategy": {
                        "type": "string",
                        "enum": ["lazy-on-fail", "every-n", "interval"],
                        "default": "lazy-on-fail"
                    },
                    "region": { "type": "string" },
                    "reason": { "type": "string" }
                }
            }),
        },
    ]
}

/// Validation outcome for `tools/call` arguments.
#[derive(Debug)]
pub enum ToolValidation {
    Ok,
    UnknownTool,
    MissingField(&'static str),
}

/// Validate the tool name + arguments and return the argv vector that
/// should be passed to `rev-stealth`. Returns `Err` if validation fails.
pub fn build_cli_argv(tool: &str, args: &Value) -> Result<Vec<String>, ToolValidation> {
    let obj = args.as_object();
    let get_str = |k: &str| -> Option<String> {
        obj.and_then(|m| m.get(k))
            .and_then(|v| v.as_str())
            .map(|s| s.to_string())
    };
    let get_bool =
        |k: &str| -> Option<bool> { obj.and_then(|m| m.get(k)).and_then(|v| v.as_bool()) };
    let get_num = |k: &str| -> Option<f64> { obj.and_then(|m| m.get(k)).and_then(|v| v.as_f64()) };

    let mut argv: Vec<String> = vec!["--format".into(), "json".into()];

    match tool {
        "spider" => {
            let url = get_str("url").ok_or(ToolValidation::MissingField("url"))?;
            argv.push("spider".into());
            argv.push("--url".into());
            argv.push(url);
            if let Some(s) = get_str("session_id") {
                argv.push("--session-id".into());
                argv.push(s);
            }
            if let Some(s) = get_str("mobile_preset") {
                argv.push("--mobile-preset".into());
                argv.push(s);
            }
            if get_bool("cf_evaluate").unwrap_or(false) {
                argv.push("--cf-evaluate".into());
            }
            if get_bool("vpn").unwrap_or(false) {
                argv.push("--vpn".into());
            }
            if let Some(s) = get_str("stable_id") {
                argv.push("--stable-id".into());
                argv.push(s);
            }
            if let Some(t) = get_num("threshold") {
                argv.push("--threshold".into());
                argv.push(format!("{t}"));
            }
            if get_bool("strict").unwrap_or(false) {
                argv.push("--strict".into());
            }
        }
        "relocate" => {
            let session_id =
                get_str("session_id").ok_or(ToolValidation::MissingField("session_id"))?;
            let stable_id =
                get_str("stable_id").ok_or(ToolValidation::MissingField("stable_id"))?;
            argv.push("relocate".into());
            argv.push("--session-id".into());
            argv.push(session_id);
            argv.push("--stable-id".into());
            argv.push(stable_id);
            if let Some(s) = get_str("html") {
                argv.push("--html".into());
                argv.push(s);
            }
            if let Some(s) = get_str("url") {
                argv.push("--url".into());
                argv.push(s);
            }
            if let Some(t) = get_num("threshold") {
                argv.push("--threshold".into());
                argv.push(format!("{t}"));
            }
        }
        "cf_evaluate" => {
            let url = get_str("url").ok_or(ToolValidation::MissingField("url"))?;
            argv.push("cf-evaluate".into());
            argv.push("--url".into());
            argv.push(url);
            if let Some(s) = get_str("session_id") {
                argv.push("--session-id".into());
                argv.push(s);
            }
        }
        "doctor" => {
            argv.push("doctor".into());
            if let Some(s) = get_str("container") {
                argv.push("--container".into());
                argv.push(s);
            }
            if let Some(s) = get_str("expected_country") {
                argv.push("--expected-country".into());
                argv.push(s);
            }
            // Doctor uses --output-format instead of --format due to legacy
            // arg-name collision (see stealth-cli main.rs cli_tests).
            // We already pushed `--format json`; doctor honors it globally.
        }
        "vpn_rotate" => {
            argv.push("vpn".into());
            argv.push("rotate".into());
            if let Some(s) = get_str("provider") {
                argv.push("--provider".into());
                argv.push(s);
            }
            if let Some(s) = get_str("strategy") {
                argv.push("--strategy".into());
                argv.push(s);
            }
            if let Some(s) = get_str("region") {
                argv.push("--region".into());
                argv.push(s);
            }
            if let Some(s) = get_str("reason") {
                argv.push("--reason".into());
                argv.push(s);
            }
        }
        _ => return Err(ToolValidation::UnknownTool),
    }

    Ok(argv)
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_tools_list_returns_15_tools() {
        let defs = tool_definitions();
        assert_eq!(defs.len(), 15);
        let names: Vec<&str> = defs.iter().map(|d| d.name).collect();
        assert!(names.contains(&"spider"));
        assert!(names.contains(&"relocate"));
        assert!(names.contains(&"cf_evaluate"));
        assert!(names.contains(&"doctor"));
        assert!(names.contains(&"vpn_rotate"));
        assert!(names.contains(&"recipe_list"));
        assert!(names.contains(&"recipe_show"));
        assert!(names.contains(&"recipe_remove"));
        assert!(names.contains(&"recipe_propose_endpoint"));
        assert!(names.contains(&"recipe_export"));
        assert!(names.contains(&"recipe_import"));
        assert!(names.contains(&"auth_login_start"));
        assert!(names.contains(&"auth_login_complete"));
        assert!(names.contains(&"auth_list"));
        assert!(names.contains(&"auth_status"));
    }

    #[test]
    fn test_tool_schemas_are_objects_with_type_object() {
        for d in tool_definitions() {
            let t = d.input_schema.get("type").and_then(|v| v.as_str());
            assert_eq!(
                t,
                Some("object"),
                "tool {} schema.type must be object",
                d.name
            );
        }
    }

    #[test]
    fn test_tools_call_unknown_tool_returns_error() {
        let res = build_cli_argv("nonexistent", &json!({}));
        assert!(matches!(res, Err(ToolValidation::UnknownTool)));
    }

    #[test]
    fn test_tools_call_invalid_input_validation_spider() {
        // spider requires url
        let res = build_cli_argv("spider", &json!({}));
        assert!(matches!(res, Err(ToolValidation::MissingField("url"))));
    }

    #[test]
    fn test_tools_call_invalid_input_validation_relocate() {
        let res = build_cli_argv("relocate", &json!({ "session_id": "s" }));
        assert!(matches!(
            res,
            Err(ToolValidation::MissingField("stable_id"))
        ));
    }

    #[test]
    fn test_build_argv_spider_full() {
        let argv = build_cli_argv(
            "spider",
            &json!({
                "url": "https://example.com",
                "session_id": "abc",
                "cf_evaluate": true,
                "strict": true,
                "threshold": 0.9
            }),
        )
        .unwrap();
        assert_eq!(&argv[0..2], &["--format", "json"]);
        assert!(argv.contains(&"spider".to_string()));
        assert!(argv.contains(&"--cf-evaluate".to_string()));
        assert!(argv.contains(&"--strict".to_string()));
        assert!(argv.contains(&"https://example.com".to_string()));
    }
}
