//! Context analysis module — replaces `context_analysis.sh`.
//!
//! Provides repo-map generation, preflight checks, delta computation,
//! deletion detection, and freshness validation — all without shelling
//! out to `jq`.

use harness_cache::{CacheManager, FileIndexEntry};
use clap::Subcommand;
use serde::{Deserialize, Serialize};
use sha2::{Digest, Sha256};
use std::collections::{BTreeSet, HashMap, HashSet};
use std::fs;
use std::io::{BufRead, BufReader};
use std::path::{Path, PathBuf};

use shared::error::{AgentError, Result};
use shared::git;

// ---------------------------------------------------------------------------
// CLI subcommands
// ---------------------------------------------------------------------------

/// Context analysis subcommands.
#[derive(Subcommand)]
pub enum ContextAction {
    /// Build or refresh the repo-map and write it to `--output`.
    Update {
        /// Path to the execution plan.
        #[arg(long)]
        plan: String,
        /// Output path for the context snapshot JSON.
        #[arg(long)]
        output: String,
        /// Only index files changed since last commit.
        #[arg(long)]
        changed_only: bool,
    },
    /// Detect files present in a baseline but missing on disk.
    DetectDeletions {
        /// Output path for the deletion report JSON.
        #[arg(long)]
        output: String,
    },
    /// Run a preflight scope/change check against a plan.
    Preflight {
        /// Path to the execution plan.
        #[arg(long)]
        plan: String,
        /// Output path for the preflight result JSON.
        #[arg(long)]
        output: String,
    },
    /// Compute the delta between two context snapshots.
    Delta {
        /// Baseline snapshot JSON path.
        #[arg(long)]
        baseline: String,
        /// Current snapshot JSON path.
        #[arg(long)]
        current: String,
        /// Output path for the delta JSON.
        #[arg(long)]
        output: String,
    },
    /// Check source-file freshness against the last sync record.
    SyncFreshness {
        /// Output path for the freshness status JSON.
        #[arg(long)]
        output: String,
    },
    /// Build a tree-sitter symbol index from a snapshot JSON.
    IndexSymbols {
        /// Snapshot JSON generated by `context update`.
        #[arg(long)]
        snapshot: String,
        /// SQLite database path shared with semantic/cache data.
        #[arg(long)]
        db_path: String,
        /// Stable project identifier.
        #[arg(long)]
        project_id: String,
    },
}

// ---------------------------------------------------------------------------
// Domain types
// ---------------------------------------------------------------------------

/// A single file entry in the repo map.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct RepoMapEntry {
    /// Relative path from the repo root.
    pub path: String,
    /// Detected programming language, if any.
    pub language: Option<String>,
    /// SHA-256 hex digest of the file contents.
    pub hash: String,
    /// Dot-separated module path derived from the file path.
    pub module: String,
    /// File size in bytes.
    pub size_bytes: u64,
}

/// Result of a preflight check.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct PreflightResult {
    /// Overall verdict.
    pub verdict: PreflightVerdict,
    /// Files with uncommitted changes.
    pub changed_files: Vec<String>,
    /// Files present in the baseline but missing on disk.
    pub deleted_files: Vec<String>,
    /// Scope analysis relative to the plan.
    pub scope_analysis: ScopeAnalysis,
    /// Human-readable warnings.
    pub warnings: Vec<String>,
}

/// Preflight verdict.
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "SCREAMING_SNAKE_CASE")]
pub enum PreflightVerdict {
    /// All checks passed.
    Pass,
    /// Non-blocking warnings exist.
    Warn,
    /// Blocking issues found — fail-closed.
    Block,
}

/// Scope analysis comparing changed files against the plan.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ScopeAnalysis {
    /// Files that fall within the plan scope.
    pub in_scope_files: Vec<String>,
    /// Files that fall outside the plan scope.
    pub out_of_scope_files: Vec<String>,
    /// Total number of changed files.
    pub total_changes: usize,
}

/// Delta between two context snapshots.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ContextDelta {
    /// Files present in current but not in baseline.
    pub added_files: Vec<String>,
    /// Files present in baseline but not in current.
    pub removed_files: Vec<String>,
    /// Files present in both but with different hashes.
    pub modified_files: Vec<String>,
}

/// Source-file freshness status.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct FreshnessStatus {
    /// Overall freshness state.
    pub status: FreshnessState,
    /// ISO-8601 timestamp of the last sync, if recorded.
    pub last_sync: Option<String>,
    /// Files whose mtime is newer than the last sync.
    pub stale_files: Vec<String>,
    /// Files referenced in the sync record but missing on disk.
    pub missing_files: Vec<String>,
}

/// Freshness state classification.
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum FreshnessState {
    /// All tracked files are up-to-date.
    Fresh,
    /// Some tracked files have been modified since last sync.
    Stale,
    /// The freshness record itself is missing.
    Missing,
    /// The freshness record is corrupt or unreadable.
    Invalid,
}

/// Point-in-time context snapshot written to disk.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ContextSnapshot {
    /// Indexed file entries.
    pub files: Vec<RepoMapEntry>,
    /// ISO-8601 timestamp when this snapshot was taken.
    pub timestamp: String,
}

// ---------------------------------------------------------------------------
// Internal freshness record (deserialized from the sync JSON)
// ---------------------------------------------------------------------------

#[derive(Debug, Clone, Serialize, Deserialize)]
struct FreshnessRecord {
    last_sync: Option<String>,
    #[serde(default)]
    files: HashMap<String, u64>,
}

// ---------------------------------------------------------------------------
// Constants
// ---------------------------------------------------------------------------

/// Directories excluded from indexing.
const EXCLUDED_DIRS: &[&str] = &[
    ".git",
    "node_modules",
    "target",
    "dist",
    "__pycache__",
    ".tox",
    ".mypy_cache",
    ".pytest_cache",
    "vendor",
    ".next",
    "build",
    ".cache",
];

/// File extensions excluded from indexing (binary / non-source).
const EXCLUDED_EXTENSIONS: &[&str] = &[
    "pyc", "pyo", "class", "o", "obj", "a", "lib", "so", "dylib", "dll", "exe", "png", "jpg",
    "jpeg", "gif", "bmp", "ico", "svg", "webp", "mp4", "avi", "mov", "mkv", "webm", "mp3", "wav",
    "ogg", "flac", "zip", "tar", "gz", "bz2", "xz", "7z", "rar", "woff", "woff2", "ttf", "eot",
    "pdf", "doc", "docx", "xls", "xlsx", "db", "sqlite", "sqlite3", "lock",
];

/// Freshness record path relative to repo root.
const FRESHNESS_PATH: &str = ".agent/context/product_surface_sync_freshness.json";

/// Default product roots from project context. Additional native roots can be
/// inferred from changed files and plan scope.
const DEFAULT_PRODUCT_ROOTS: &[&str] = &["src", "apps", "packages", "services"];

/// Harness-owned paths that should not be treated as product roots.
const HARNESS_PREFIXES: &[&str] = &[
    ".agent/",
    ".agent_rules/",
    ".claude/",
    ".codex/",
    "docs/",
    "scripts/",
    "setup/",
    "workspace/",
    "test/integration/",
];

/// Root-level harness files.
const HARNESS_FILES: &[&str] = &["AGENTS.md", "CLAUDE.md"];

// ---------------------------------------------------------------------------
// Public helpers
// ---------------------------------------------------------------------------

/// Detect the programming language from a file's extension, falling back to
/// shebang inspection.
pub fn detect_language(path: &Path) -> Option<String> {
    if let Some(ext) = path.extension().and_then(|e| e.to_str()) {
        let lang = match ext.to_lowercase().as_str() {
            "rs" => "rust",
            "ts" => "typescript",
            "tsx" => "typescript",
            "jsx" => "typescript",
            "js" => "javascript",
            "mjs" => "javascript",
            "cjs" => "javascript",
            "py" => "python",
            "go" => "go",
            "sh" | "bash" | "zsh" => "shell",
            "java" => "java",
            "rb" => "ruby",
            "cpp" | "cc" | "cxx" | "c" | "h" | "hpp" | "hxx" => "c/cpp",
            "cs" => "csharp",
            "swift" => "swift",
            "kt" | "kts" => "kotlin",
            "scala" => "scala",
            "lua" => "lua",
            "r" => "r",
            "pl" | "pm" => "perl",
            "php" => "php",
            "ex" | "exs" => "elixir",
            "erl" | "hrl" => "erlang",
            "hs" => "haskell",
            "ml" | "mli" => "ocaml",
            "clj" | "cljs" | "cljc" => "clojure",
            "dart" => "dart",
            "zig" => "zig",
            "nim" => "nim",
            "toml" => "toml",
            "yaml" | "yml" => "yaml",
            "json" => "json",
            "md" | "markdown" => "markdown",
            "sql" => "sql",
            "proto" => "protobuf",
            "graphql" | "gql" => "graphql",
            "css" => "css",
            "scss" | "sass" => "sass",
            "less" => "less",
            "html" | "htm" => "html",
            "xml" => "xml",
            "vue" => "vue",
            "svelte" => "svelte",
            _ => return shebang_language(path),
        };
        Some(lang.to_string())
    } else {
        shebang_language(path)
    }
}

/// Compute the SHA-256 hex digest of a file's contents.
pub fn compute_file_hash(path: &Path) -> Result<String> {
    let data = fs::read(path)?;
    let mut hasher = Sha256::new();
    hasher.update(&data);
    let digest = hasher.finalize();
    Ok(hex::encode(digest))
}

/// Decide whether a path should be indexed.
///
/// Returns `false` for paths inside excluded directories or with excluded
/// extensions.
pub fn should_index_file(path: &Path) -> bool {
    // Check excluded directories
    for component in path.components() {
        if let std::path::Component::Normal(name) = component {
            if let Some(name_str) = name.to_str() {
                if EXCLUDED_DIRS.contains(&name_str) {
                    return false;
                }
            }
        }
    }

    // Check excluded extensions
    if let Some(ext) = path.extension().and_then(|e| e.to_str()) {
        if EXCLUDED_EXTENSIONS.contains(&ext.to_lowercase().as_str()) {
            return false;
        }
    }

    // Exclude hidden files (starting with .)
    if let Some(name) = path.file_name().and_then(|n| n.to_str()) {
        if name.starts_with('.') && name != ".gitignore" && name != ".editorconfig" {
            return false;
        }
    }

    true
}

/// Collect files changed since the last commit plus untracked files.
pub fn collect_changed_files() -> Result<Vec<PathBuf>> {
    let mut files: HashSet<PathBuf> = HashSet::new();

    // Staged + unstaged changes
    if let Ok(changed) = git::git_changed_files() {
        for f in changed {
            files.insert(PathBuf::from(f));
        }
    }

    // Untracked files
    if let Ok(untracked) = git::git_ls_files_untracked() {
        for f in untracked {
            files.insert(PathBuf::from(f));
        }
    }

    let mut result: Vec<PathBuf> = files.into_iter().collect();
    result.sort();
    Ok(result)
}

/// Strip the repo root prefix from each path, producing repo-relative strings.
pub fn normalize_paths(paths: &[PathBuf], repo_root: &Path) -> Vec<String> {
    paths
        .iter()
        .filter_map(|p| {
            let full = if p.is_absolute() {
                p.clone()
            } else {
                repo_root.join(p)
            };
            full.strip_prefix(repo_root)
                .ok()
                .map(|rel| rel.to_string_lossy().to_string())
        })
        .collect()
}

fn normalize_repo_path(path: &str) -> String {
    let mut normalized = path.trim().replace('\\', "/");
    while normalized.starts_with("./") {
        normalized = normalized[2..].to_string();
    }
    while normalized.contains("//") {
        normalized = normalized.replace("//", "/");
    }
    normalized.trim_end_matches('/').to_string()
}

fn path_has_prefix(path: &str, prefix: &str) -> bool {
    let path = normalize_repo_path(path);
    let prefix = normalize_repo_path(prefix);
    path == prefix
        || path
            .strip_prefix(&prefix)
            .is_some_and(|rest| rest.starts_with('/'))
}

fn is_harness_owned_path(path: &str) -> bool {
    let normalized = normalize_repo_path(path);
    HARNESS_FILES.contains(&normalized.as_str())
        || HARNESS_PREFIXES
            .iter()
            .any(|prefix| path_has_prefix(&normalized, prefix))
}

fn first_path_component(path: &str) -> Option<String> {
    let normalized = normalize_repo_path(path);
    Path::new(&normalized).components().find_map(|component| {
        if let std::path::Component::Normal(name) = component {
            name.to_str().map(ToString::to_string)
        } else {
            None
        }
    })
}

fn collect_candidate_product_roots(paths: &[String]) -> Vec<String> {
    let mut roots = BTreeSet::new();
    for path in paths {
        let normalized = normalize_repo_path(path);
        if normalized.is_empty() || is_harness_owned_path(&normalized) {
            continue;
        }
        if normalized.split('/').count() < 2 {
            continue;
        }
        if let Some(root) = first_path_component(&normalized) {
            roots.insert(root);
        }
    }
    roots.into_iter().collect()
}

fn resolve_active_product_roots(
    repo_root: &Path,
    plan_content: Option<&str>,
    candidate_paths: &[PathBuf],
) -> Vec<String> {
    let mut roots = BTreeSet::new();

    for root in DEFAULT_PRODUCT_ROOTS {
        if repo_root.join(root).exists() {
            roots.insert((*root).to_string());
        }
    }

    let normalized_candidates = normalize_paths(candidate_paths, repo_root);
    for root in collect_candidate_product_roots(&normalized_candidates) {
        roots.insert(root);
    }

    if let Some(plan_content) = plan_content {
        let scope_paths = extract_scope_paths(plan_content);
        for root in collect_candidate_product_roots(&scope_paths) {
            roots.insert(root);
        }
    }

    roots.into_iter().collect()
}

fn filter_paths_by_roots(paths: &[String], roots: &[String]) -> Vec<String> {
    let mut filtered = Vec::new();

    for path in paths {
        let normalized = normalize_repo_path(path);
        if normalized.is_empty() || is_harness_owned_path(&normalized) {
            continue;
        }
        if roots.is_empty() || roots.iter().any(|root| path_has_prefix(&normalized, root)) {
            filtered.push(normalized);
        }
    }

    filtered
}

fn filter_pathbufs_by_roots(paths: &[PathBuf], repo_root: &Path, roots: &[String]) -> Vec<PathBuf> {
    let normalized = normalize_paths(paths, repo_root);
    let allowed: HashSet<String> = filter_paths_by_roots(&normalized, roots)
        .into_iter()
        .collect();

    paths
        .iter()
        .filter_map(|path| {
            let normalized = if path.is_absolute() {
                path.strip_prefix(repo_root)
                    .ok()
                    .map(|rel| rel.to_string_lossy().to_string())
            } else {
                Some(path.to_string_lossy().to_string())
            }?;
            let normalized = normalize_repo_path(&normalized);
            if allowed.contains(&normalized) {
                Some(path.clone())
            } else {
                None
            }
        })
        .collect()
}

/// Build a [`RepoMapEntry`] for a single file.
pub fn build_repomap_entry(path: &Path, repo_root: &Path) -> Result<RepoMapEntry> {
    let abs_path = if path.is_absolute() {
        path.to_path_buf()
    } else {
        repo_root.join(path)
    };

    let rel = abs_path
        .strip_prefix(repo_root)
        .map_err(|_| {
            AgentError::Validation(format!(
                "path {} is not under repo root {}",
                abs_path.display(),
                repo_root.display()
            ))
        })?
        .to_string_lossy()
        .to_string();

    let language = detect_language(&abs_path);
    let hash = compute_file_hash(&abs_path)?;
    let module = module_from_file(&rel);
    let metadata = fs::metadata(&abs_path)?;

    Ok(RepoMapEntry {
        path: rel,
        language,
        hash,
        module,
        size_bytes: metadata.len(),
    })
}

/// Derive a dot-separated module path from a relative file path.
///
/// Example: `"apps/web/src/foo.rs"` → `"apps.web.src.foo"`
pub fn module_from_file(path: &str) -> String {
    let p = Path::new(path);
    let without_ext = p.with_extension("");
    without_ext.to_string_lossy().replace(['/', '\\'], ".")
}

/// Detect files present in `baseline_files` but absent from `current_files`.
pub fn detect_deletions(baseline_files: &[String], current_files: &[String]) -> Vec<String> {
    let current_set: HashSet<&String> = current_files.iter().collect();
    baseline_files
        .iter()
        .filter(|f| !current_set.contains(f))
        .cloned()
        .collect()
}

/// Run a preflight scope/change check.
///
/// Reads the plan to extract scope paths, then compares against the current
/// working tree to classify changes as in-scope or out-of-scope.
pub fn preflight_check(plan_path: &Path, output: &Path) -> Result<PreflightResult> {
    let plan_content = fs::read_to_string(plan_path)
        .map_err(|e| AgentError::NotFound(format!("plan file {}: {e}", plan_path.display())))?;

    let scope_paths = extract_scope_paths(&plan_content);
    let changed = collect_changed_files()?;

    let repo_root = git::git_repo_root()?;
    let changed_strs = normalize_paths(&changed, &repo_root);

    let mut in_scope = Vec::new();
    let mut out_of_scope = Vec::new();

    for file in &changed_strs {
        if is_in_scope(file, &scope_paths) {
            in_scope.push(file.clone());
        } else {
            out_of_scope.push(file.clone());
        }
    }

    let mut warnings = Vec::new();
    let verdict = if out_of_scope.is_empty() {
        PreflightVerdict::Pass
    } else {
        warnings.push(format!(
            "{} file(s) changed outside plan scope",
            out_of_scope.len()
        ));
        PreflightVerdict::Warn
    };

    let result = PreflightResult {
        verdict,
        changed_files: changed_strs.clone(),
        deleted_files: Vec::new(),
        scope_analysis: ScopeAnalysis {
            in_scope_files: in_scope,
            out_of_scope_files: out_of_scope,
            total_changes: changed_strs.len(),
        },
        warnings,
    };

    write_json_atomic(output, &result)?;
    Ok(result)
}

/// Compute the delta between two context snapshots.
pub fn context_delta(baseline: &Path, current: &Path) -> Result<ContextDelta> {
    let base_snap: ContextSnapshot = read_json(baseline)?;
    let curr_snap: ContextSnapshot = read_json(current)?;

    let base_map: HashMap<&str, &str> = base_snap
        .files
        .iter()
        .map(|e| (e.path.as_str(), e.hash.as_str()))
        .collect();

    let curr_map: HashMap<&str, &str> = curr_snap
        .files
        .iter()
        .map(|e| (e.path.as_str(), e.hash.as_str()))
        .collect();

    let mut added = Vec::new();
    let mut removed = Vec::new();
    let mut modified = Vec::new();

    for (path, hash) in &curr_map {
        match base_map.get(path) {
            None => added.push(path.to_string()),
            Some(base_hash) if base_hash != hash => modified.push(path.to_string()),
            _ => {}
        }
    }

    for path in base_map.keys() {
        if !curr_map.contains_key(path) {
            removed.push(path.to_string());
        }
    }

    added.sort();
    removed.sort();
    modified.sort();

    Ok(ContextDelta {
        added_files: added,
        removed_files: removed,
        modified_files: modified,
    })
}

/// Check source-file freshness against the sync record.
pub fn src_sync_freshness(repo_root: &Path) -> Result<FreshnessStatus> {
    let freshness_file = repo_root.join(FRESHNESS_PATH);

    if !freshness_file.exists() {
        return Ok(FreshnessStatus {
            status: FreshnessState::Missing,
            last_sync: None,
            stale_files: Vec::new(),
            missing_files: Vec::new(),
        });
    }

    let record: FreshnessRecord = match read_json(&freshness_file) {
        Ok(r) => r,
        Err(_) => {
            return Ok(FreshnessStatus {
                status: FreshnessState::Invalid,
                last_sync: None,
                stale_files: Vec::new(),
                missing_files: Vec::new(),
            });
        }
    };

    let mut stale = Vec::new();
    let mut missing = Vec::new();

    for (path, recorded_mtime) in &record.files {
        let full = repo_root.join(path);
        if !full.exists() {
            missing.push(path.clone());
            continue;
        }
        match file_mtime_epoch(&full) {
            Ok(current_mtime) if current_mtime > *recorded_mtime => {
                stale.push(path.clone());
            }
            Ok(_) => {}
            Err(_) => {
                stale.push(path.clone());
            }
        }
    }

    stale.sort();
    missing.sort();

    let status = if missing.is_empty() && stale.is_empty() {
        FreshnessState::Fresh
    } else {
        FreshnessState::Stale
    };

    Ok(FreshnessStatus {
        status,
        last_sync: record.last_sync,
        stale_files: stale,
        missing_files: missing,
    })
}

/// Return the modification time of a file as seconds since the Unix epoch.
pub fn file_mtime_epoch(path: &Path) -> Result<u64> {
    let meta = fs::metadata(path)?;
    let mtime = meta.modified().map_err(AgentError::Io)?;
    let epoch = mtime
        .duration_since(std::time::UNIX_EPOCH)
        .map_err(|e| AgentError::State(format!("mtime before epoch: {e}")))?;
    Ok(epoch.as_secs())
}

/// Keep only files that belong to active product roots.
#[cfg(test)]
fn filter_src_files(files: &[String]) -> Vec<String> {
    let roots = collect_candidate_product_roots(files);
    filter_paths_by_roots(files, &roots)
}

/// Build a full context snapshot (repo map) and write it as JSON.
pub fn context_update(
    plan: &Path,
    output: &Path,
    changed_only: bool,
    cache: Option<&mut CacheManager>,
) -> Result<()> {
    let repo_root = git::git_repo_root()?;
    let plan_content = fs::read_to_string(plan).ok();

    let candidate_files: Vec<PathBuf> = if changed_only {
        collect_changed_files()?
    } else {
        collect_all_files(&repo_root)?
    };
    let active_roots =
        resolve_active_product_roots(&repo_root, plan_content.as_deref(), &candidate_files);
    let files_to_index = filter_pathbufs_by_roots(&candidate_files, &repo_root, &active_roots);

    let mut entries = Vec::new();
    for file_path in &files_to_index {
        let abs = if file_path.is_absolute() {
            file_path.clone()
        } else {
            repo_root.join(file_path)
        };

        if !abs.is_file() || !should_index_file(file_path) {
            continue;
        }

        match build_repomap_entry(&abs, &repo_root) {
            Ok(entry) => entries.push(entry),
            Err(e) => {
                tracing::warn!(
                    path = %file_path.display(),
                    error = %e,
                    "skipping file due to indexing error"
                );
            }
        }
    }

    entries.sort_by(|a, b| a.path.cmp(&b.path));

    let snapshot = ContextSnapshot {
        files: entries,
        timestamp: chrono::Utc::now().to_rfc3339(),
    };

    write_json_atomic(output, &snapshot)?;

    if let Some(cache) = cache {
        for entry in &snapshot.files {
            cache.update_file_index(&FileIndexEntry {
                file_path: entry.path.clone(),
                content_hash: entry.hash.clone(),
                size_bytes: entry.size_bytes,
                last_indexed_at: snapshot.timestamp.clone(),
            })?;
        }
    }

    tracing::info!(
        output = %output.display(),
        file_count = snapshot.files.len(),
        "context snapshot written"
    );
    Ok(())
}

/// Build a tree-sitter symbol index using file entries from a snapshot JSON.
pub fn index_symbols_from_snapshot(
    snapshot: &Path,
    db_path: &Path,
    project_id: &str,
) -> Result<tree_sitter_index::IndexResult> {
    let repo_root = git::git_repo_root()?;
    let snapshot_data: ContextSnapshot = read_json(snapshot)?;

    let files: Vec<(PathBuf, String, String)> = snapshot_data
        .files
        .into_iter()
        .filter_map(|entry| {
            entry
                .language
                .map(|language| (repo_root.join(entry.path), language, entry.hash))
        })
        .collect();

    tree_sitter_index::index_files_at_path(
        &db_path.to_string_lossy(),
        project_id,
        &files,
        &tree_sitter_index::IndexConfig::default(),
        true,
    )
}

/// Entry point — dispatch a [`ContextAction`] subcommand.
///
/// This is the main entry called from `main.rs`.
pub fn run(action: ContextAction) -> Result<()> {
    execute(action)
}

/// Dispatch a [`ContextAction`] subcommand.
pub fn execute(action: ContextAction) -> Result<()> {
    match action {
        ContextAction::Update {
            plan,
            output,
            changed_only,
        } => context_update(Path::new(&plan), Path::new(&output), changed_only, None),

        ContextAction::DetectDeletions { output } => {
            let repo_root = git::git_repo_root()?;
            let freshness_file = repo_root.join(FRESHNESS_PATH);

            let baseline_files = if freshness_file.exists() {
                let record: FreshnessRecord = read_json(&freshness_file)?;
                record.files.keys().cloned().collect::<Vec<_>>()
            } else {
                Vec::new()
            };

            let current_files = collect_all_files(&repo_root)?
                .iter()
                .filter_map(|p| {
                    p.strip_prefix(&repo_root)
                        .ok()
                        .map(|r| r.to_string_lossy().to_string())
                })
                .collect::<Vec<_>>();

            let deleted = detect_deletions(&baseline_files, &current_files);
            write_json_atomic(Path::new(&output), &deleted)?;
            Ok(())
        }

        ContextAction::Preflight { plan, output } => {
            preflight_check(Path::new(&plan), Path::new(&output))?;
            Ok(())
        }

        ContextAction::Delta {
            baseline,
            current,
            output,
        } => {
            let delta = context_delta(Path::new(&baseline), Path::new(&current))?;
            write_json_atomic(Path::new(&output), &delta)?;
            Ok(())
        }

        ContextAction::SyncFreshness { output } => {
            let repo_root = git::git_repo_root()?;
            let status = src_sync_freshness(&repo_root)?;
            write_json_atomic(Path::new(&output), &status)?;
            Ok(())
        }
        ContextAction::IndexSymbols {
            snapshot,
            db_path,
            project_id,
        } => {
            let result = index_symbols_from_snapshot(
                Path::new(&snapshot),
                Path::new(&db_path),
                &project_id,
            )?;
            let json = serde_json::to_string_pretty(&result).map_err(AgentError::Json)?;
            println!("{json}");
            Ok(())
        }
    }
}

// ---------------------------------------------------------------------------
// Internal helpers
// ---------------------------------------------------------------------------

/// Attempt to detect language from a shebang line.
fn shebang_language(path: &Path) -> Option<String> {
    let file = fs::File::open(path).ok()?;
    let reader = BufReader::new(file);
    let first_line = reader.lines().next()?.ok()?;

    if !first_line.starts_with("#!") {
        return None;
    }

    let line = first_line.to_lowercase();
    if line.contains("python") {
        Some("python".to_string())
    } else if line.contains("bash") || line.contains("/sh") {
        Some("shell".to_string())
    } else if line.contains("node") || line.contains("deno") || line.contains("bun") {
        Some("javascript".to_string())
    } else if line.contains("ruby") {
        Some("ruby".to_string())
    } else if line.contains("perl") {
        Some("perl".to_string())
    } else if line.contains("php") {
        Some("php".to_string())
    } else {
        None
    }
}

/// Extract scope paths from a plan file.
///
/// Looks for lines like `- path: apps/web/src/foo.rs` or file-path patterns
/// inside fenced blocks.
fn extract_scope_paths(plan_content: &str) -> Vec<String> {
    let mut paths = Vec::new();

    for line in plan_content.lines() {
        let trimmed = line.trim();

        // Match "- path: ..." or "- file: ..."
        for prefix in &["- path:", "- file:", "- target:"] {
            if let Some(rest) = trimmed.strip_prefix(prefix) {
                let p = rest.trim().trim_matches('`').trim_matches('"');
                if !p.is_empty() {
                    paths.push(p.to_string());
                }
            }
        }

        // Match backtick-quoted file paths that look like source files
        if trimmed.contains('`') {
            for segment in trimmed.split('`') {
                let s = segment.trim();
                if (s.contains('/') || s.contains('\\'))
                    && !s.contains(' ')
                    && s.len() < 256
                    && (s.ends_with(".rs")
                        || s.ends_with(".ts")
                        || s.ends_with(".py")
                        || s.ends_with(".go")
                        || s.ends_with(".js")
                        || s.ends_with(".sh")
                        || s.ends_with(".java")
                        || s.ends_with(".rb")
                        || s.ends_with(".cpp")
                        || s.ends_with(".c")
                        || s.ends_with(".toml")
                        || s.ends_with(".json")
                        || s.ends_with(".yaml")
                        || s.ends_with(".yml")
                        || s.ends_with(".md"))
                {
                    paths.push(s.to_string());
                }
            }
        }
    }

    paths.sort();
    paths.dedup();
    paths
}

/// Check whether a file path is "in scope" relative to the extracted scope paths.
fn is_in_scope(file: &str, scope_paths: &[String]) -> bool {
    if scope_paths.is_empty() {
        // No scope defined — everything is in scope.
        return true;
    }
    scope_paths.iter().any(|scope| path_has_prefix(file, scope))
}

/// Recursively collect all files under `root`, excluding directories that
/// should not be indexed.
fn collect_all_files(root: &Path) -> Result<Vec<PathBuf>> {
    let mut result = Vec::new();
    collect_files_recursive(root, &mut result)?;
    Ok(result)
}

fn collect_files_recursive(dir: &Path, out: &mut Vec<PathBuf>) -> Result<()> {
    let entries = fs::read_dir(dir)?;
    for entry in entries {
        let entry = entry?;
        let path = entry.path();
        let file_type = entry.file_type()?;

        if file_type.is_dir() {
            if let Some(name) = path.file_name().and_then(|n| n.to_str()) {
                if EXCLUDED_DIRS.contains(&name) || name.starts_with('.') {
                    continue;
                }
            }
            collect_files_recursive(&path, out)?;
        } else if file_type.is_file() {
            out.push(path);
        }
    }
    Ok(())
}

/// Read and deserialize JSON from a file.
fn read_json<T: serde::de::DeserializeOwned>(path: &Path) -> Result<T> {
    let content = fs::read_to_string(path)
        .map_err(|e| AgentError::NotFound(format!("{}: {e}", path.display())))?;
    serde_json::from_str(&content).map_err(AgentError::Json)
}

/// Atomically write JSON to a file (write to tmp, then rename).
fn write_json_atomic<T: Serialize>(path: &Path, value: &T) -> Result<()> {
    use std::io::Write;
    use tempfile::NamedTempFile;

    let json = serde_json::to_string_pretty(value)?;

    let parent = path.parent().unwrap_or(Path::new("."));
    fs::create_dir_all(parent)?;

    let mut tmp = NamedTempFile::new_in(parent)?;
    tmp.write_all(json.as_bytes())?;
    tmp.persist(path).map_err(|e| e.error)?;

    Ok(())
}

// ---------------------------------------------------------------------------
// Tests
// ---------------------------------------------------------------------------

#[cfg(test)]
mod tests {
    use super::*;
    use std::path::Path;

    // -- detect_language -------------------------------------------------------

    #[test]
    fn detect_language_rust() {
        assert_eq!(
            detect_language(Path::new("src/main.rs")),
            Some("rust".to_string())
        );
    }

    #[test]
    fn detect_language_typescript_tsx() {
        assert_eq!(
            detect_language(Path::new("app/page.tsx")),
            Some("typescript".to_string())
        );
        assert_eq!(
            detect_language(Path::new("app/page.ts")),
            Some("typescript".to_string())
        );
    }

    #[test]
    fn detect_language_python() {
        assert_eq!(
            detect_language(Path::new("script.py")),
            Some("python".to_string())
        );
    }

    #[test]
    fn detect_language_go() {
        assert_eq!(
            detect_language(Path::new("main.go")),
            Some("go".to_string())
        );
    }

    #[test]
    fn detect_language_javascript() {
        assert_eq!(
            detect_language(Path::new("index.js")),
            Some("javascript".to_string())
        );
        assert_eq!(
            detect_language(Path::new("module.mjs")),
            Some("javascript".to_string())
        );
    }

    #[test]
    fn detect_language_shell() {
        assert_eq!(
            detect_language(Path::new("setup.sh")),
            Some("shell".to_string())
        );
    }

    #[test]
    fn detect_language_c_cpp() {
        assert_eq!(
            detect_language(Path::new("main.c")),
            Some("c/cpp".to_string())
        );
        assert_eq!(
            detect_language(Path::new("lib.cpp")),
            Some("c/cpp".to_string())
        );
        assert_eq!(
            detect_language(Path::new("header.h")),
            Some("c/cpp".to_string())
        );
    }

    #[test]
    fn detect_language_unknown_ext_no_shebang() {
        assert_eq!(detect_language(Path::new("data.xyz")), None);
    }

    #[test]
    fn detect_language_no_extension() {
        // File does not exist on disk, so shebang fallback returns None.
        assert_eq!(detect_language(Path::new("Makefile")), None);
    }

    // -- should_index_file -----------------------------------------------------

    #[test]
    fn should_index_normal_source() {
        assert!(should_index_file(Path::new("src/main.rs")));
        assert!(should_index_file(Path::new("lib/utils.ts")));
    }

    #[test]
    fn should_not_index_git() {
        assert!(!should_index_file(Path::new(".git/config")));
        assert!(!should_index_file(Path::new(".git/HEAD")));
    }

    #[test]
    fn should_not_index_node_modules() {
        assert!(!should_index_file(Path::new("node_modules/foo/index.js")));
    }

    #[test]
    fn should_not_index_target() {
        assert!(!should_index_file(Path::new("target/debug/build/lib.rs")));
    }

    #[test]
    fn should_not_index_pycache() {
        assert!(!should_index_file(Path::new("__pycache__/mod.cpython.pyc")));
    }

    #[test]
    fn should_not_index_binary_extensions() {
        assert!(!should_index_file(Path::new("image.png")));
        assert!(!should_index_file(Path::new("video.mp4")));
        assert!(!should_index_file(Path::new("lib.so")));
        assert!(!should_index_file(Path::new("archive.zip")));
        assert!(!should_index_file(Path::new("compiled.pyc")));
    }

    #[test]
    fn should_not_index_hidden_files() {
        assert!(!should_index_file(Path::new(".env")));
        assert!(!should_index_file(Path::new(".secrets")));
    }

    #[test]
    fn should_index_gitignore() {
        assert!(should_index_file(Path::new(".gitignore")));
    }

    // -- module_from_file ------------------------------------------------------

    #[test]
    fn module_from_file_basic() {
        assert_eq!(module_from_file("src/foo/bar.rs"), "src.foo.bar");
    }

    #[test]
    fn module_from_file_nested() {
        assert_eq!(
            module_from_file("crates/shared/src/lib.rs"),
            "crates.shared.src.lib"
        );
    }

    #[test]
    fn module_from_file_no_extension() {
        assert_eq!(module_from_file("Makefile"), "Makefile");
    }

    #[test]
    fn module_from_file_single() {
        assert_eq!(module_from_file("main.py"), "main");
    }

    // -- detect_deletions ------------------------------------------------------

    #[test]
    fn detect_deletions_empty() {
        let result = detect_deletions(&[], &[]);
        assert!(result.is_empty());
    }

    #[test]
    fn detect_deletions_none_deleted() {
        let baseline = vec!["a.rs".to_string(), "b.rs".to_string()];
        let current = vec!["a.rs".to_string(), "b.rs".to_string(), "c.rs".to_string()];
        let result = detect_deletions(&baseline, &current);
        assert!(result.is_empty());
    }

    #[test]
    fn detect_deletions_some_deleted() {
        let baseline = vec!["a.rs".to_string(), "b.rs".to_string(), "c.rs".to_string()];
        let current = vec!["a.rs".to_string()];
        let result = detect_deletions(&baseline, &current);
        assert_eq!(result, vec!["b.rs".to_string(), "c.rs".to_string()]);
    }

    #[test]
    fn detect_deletions_all_deleted() {
        let baseline = vec!["x.rs".to_string(), "y.rs".to_string()];
        let current: Vec<String> = vec![];
        let result = detect_deletions(&baseline, &current);
        assert_eq!(result.len(), 2);
    }

    // -- product root resolution -----------------------------------------------

    #[test]
    fn collect_candidate_product_roots_prefers_native_layouts() {
        let paths = vec![
            "apps/web/src/main.ts".to_string(),
            "packages/ui/src/button.tsx".to_string(),
            "services/api/src/lib.rs".to_string(),
            "app/page.tsx".to_string(),
            "docs/manual/guide.md".to_string(),
            ".agent/active/plan.md".to_string(),
        ];
        let roots = collect_candidate_product_roots(&paths);
        assert_eq!(roots, vec!["app", "apps", "packages", "services"]);
    }

    #[test]
    fn resolve_active_product_roots_combines_defaults_and_candidates() {
        let dir = tempfile::tempdir().unwrap();
        fs::create_dir_all(dir.path().join("apps/web")).unwrap();
        fs::create_dir_all(dir.path().join("packages/ui")).unwrap();

        let candidates = vec![
            PathBuf::from("app/page.tsx"),
            PathBuf::from("docs/manual/guide.md"),
            PathBuf::from("packages/ui/src/button.tsx"),
        ];

        let roots = resolve_active_product_roots(
            dir.path(),
            Some("- path: services/api/src/main.rs"),
            &candidates,
        );
        assert_eq!(roots, vec!["app", "apps", "packages", "services"]);
    }

    // -- filter_src_files ------------------------------------------------------

    #[test]
    fn filter_src_files_basic() {
        let files = vec![
            "apps/web/src/main.rs".to_string(),
            "docs/readme.md".to_string(),
            "packages/ui/src/lib.rs".to_string(),
            "scripts/check.sh".to_string(),
            "app/page.tsx".to_string(),
        ];
        let result = filter_src_files(&files);
        assert_eq!(
            result,
            vec![
                "apps/web/src/main.rs",
                "packages/ui/src/lib.rs",
                "app/page.tsx",
            ]
        );
    }

    // -- is_in_scope -----------------------------------------------------------

    #[test]
    fn in_scope_empty_scope_allows_all() {
        assert!(is_in_scope("anything/foo.rs", &[]));
    }

    #[test]
    fn in_scope_matching() {
        let scopes = vec!["apps".to_string()];
        assert!(is_in_scope("apps/web/src/context.rs", &scopes));
        assert!(!is_in_scope("tests/integration.rs", &scopes));
        assert!(!is_in_scope("apps2/web/src/context.rs", &scopes));
    }

    // -- extract_scope_paths ---------------------------------------------------

    #[test]
    fn extract_scope_from_plan() {
        let plan = r#"
## Files
- path: apps/web/src/foo.rs
- file: packages/ui/src/bar.rs
Some text mentioning `services/api/src/baz.rs` inline.
"#;
        let paths = extract_scope_paths(plan);
        assert!(paths.contains(&"apps/web/src/foo.rs".to_string()));
        assert!(paths.contains(&"packages/ui/src/bar.rs".to_string()));
        assert!(paths.contains(&"services/api/src/baz.rs".to_string()));
    }

    // -- context_delta ---------------------------------------------------------

    #[test]
    fn context_delta_computes_correctly() {
        let dir = tempfile::tempdir().unwrap();

        let base = ContextSnapshot {
            files: vec![
                RepoMapEntry {
                    path: "a.rs".into(),
                    language: Some("rust".into()),
                    hash: "aaa".into(),
                    module: "a".into(),
                    size_bytes: 100,
                },
                RepoMapEntry {
                    path: "b.rs".into(),
                    language: Some("rust".into()),
                    hash: "bbb".into(),
                    module: "b".into(),
                    size_bytes: 200,
                },
            ],
            timestamp: "2025-01-01T00:00:00Z".into(),
        };

        let curr = ContextSnapshot {
            files: vec![
                RepoMapEntry {
                    path: "a.rs".into(),
                    language: Some("rust".into()),
                    hash: "aaa_modified".into(),
                    module: "a".into(),
                    size_bytes: 110,
                },
                RepoMapEntry {
                    path: "c.rs".into(),
                    language: Some("rust".into()),
                    hash: "ccc".into(),
                    module: "c".into(),
                    size_bytes: 300,
                },
            ],
            timestamp: "2025-01-02T00:00:00Z".into(),
        };

        let base_path = dir.path().join("base.json");
        let curr_path = dir.path().join("curr.json");

        fs::write(&base_path, serde_json::to_string(&base).unwrap()).unwrap();
        fs::write(&curr_path, serde_json::to_string(&curr).unwrap()).unwrap();

        let delta = context_delta(&base_path, &curr_path).unwrap();
        assert_eq!(delta.added_files, vec!["c.rs"]);
        assert_eq!(delta.removed_files, vec!["b.rs"]);
        assert_eq!(delta.modified_files, vec!["a.rs"]);
    }
}
