// SPDX-License-Identifier: MIT
// Source: vendored from rev_stealth crates @ 6fc38fd
//! Chromiumoxide-backed stealth browser launcher.
//!
//! This module materialises a [`StealthProfile`] into a live
//! [`chromiumoxide::Browser`]. It stitches three concerns together:
//!
//! 1. **Process configuration** — UA / viewport / mobile emulation are set
//!    on the [`BrowserConfig`] so the headless Chromium starts with the
//!    right shape from the very first request (User-Agent header, accept
//!    language, viewport size, has_touch).
//! 2. **CDP-level emulation** — `Emulation.setUserAgentOverride` and
//!    `Network.setExtraHTTPHeaders` cover the headers that
//!    `BrowserConfig` does not let us set declaratively (Sec-CH-UA,
//!    Accept-Language).
//! 3. **JS bootstrap** — every per-page `Page.addScriptToEvaluateOnNewDocument`
//!    runs the patch bundle generated by [`mobile_fp::patches`] *before*
//!    any site script executes, so detectors that probe `navigator.*` see
//!    the spoofed values.
//!
//! ## Lifetime model
//!
//! [`StealthBrowser`] owns the chromiumoxide [`Browser`] handle plus the
//! background event-loop task. Drop terminates the chrome process and
//! aborts the loop; closure is also exposed explicitly via
//! [`StealthBrowser::shutdown`] when graceful teardown matters.

use std::time::Duration;

use chromiumoxide::browser::{Browser, BrowserConfig};
use chromiumoxide::cdp::browser_protocol::emulation::SetUserAgentOverrideParams;
use chromiumoxide::cdp::browser_protocol::network::SetExtraHttpHeadersParams;
use chromiumoxide::handler::viewport::Viewport;
use chromiumoxide::Page;
use futures::StreamExt;
use mobile_fp::Fingerprint;
use serde_json::json;
use tokio::task::JoinHandle;
use tracing::{debug, info, warn};

use crate::{Result, StealthError, StealthLevel, StealthProfile};

/// JS bootstrap script applied to every new document.
///
/// The composition is:
///
/// * [`StealthLevel::Off`] -> empty (no patches).
/// * [`StealthLevel::Basic`] -> `webdriver` + `chrome.runtime` only.
/// * [`StealthLevel::Full`] + non-desktop profile -> the entire fingerprint
///   bundle from [`mobile_fp::patches::full_bootstrap`].
/// * [`StealthLevel::Full`] + desktop profile -> the static patches (no
///   mobile fingerprint overrides), so this also unblocks
///   `bot.sannysoft.com` even without mobile emulation.
pub fn bootstrap_js(profile: &StealthProfile) -> String {
    use mobile_fp::patches::{
        chrome_runtime_patch, full_bootstrap, plugins_patch, webdriver_patch,
    };

    match (profile.stealth_level, profile.browser_profile.preset()) {
        (StealthLevel::Off, _) => String::new(),
        (StealthLevel::Basic, _) => {
            let mut s = String::with_capacity(2048);
            s.push_str(webdriver_patch());
            s.push('\n');
            s.push_str(chrome_runtime_patch());
            s
        }
        (StealthLevel::Full, Some(preset_id)) => full_bootstrap(&preset_id.fingerprint()),
        // Desktop + Full: static patches without the mobile-FP overrides.
        (StealthLevel::Full, None) => {
            let mut s = String::with_capacity(4096);
            s.push_str(webdriver_patch());
            s.push('\n');
            s.push_str(chrome_runtime_patch());
            s.push('\n');
            s.push_str(plugins_patch());
            s
        }
    }
}

/// Build a [`BrowserConfig`] for the given profile.
///
/// Public so callers (tests, integration sweeps, CLI) can introspect the
/// configuration before calling [`launch_stealth`] — useful for assertions
/// like "viewport matches the iPhone 15 Pro spec".
pub fn build_browser_config(profile: &StealthProfile) -> Result<BrowserConfig> {
    let preset_fp = profile.browser_profile.preset().map(|p| p.fingerprint());

    let viewport = match &preset_fp {
        Some(fp) => Viewport {
            width: fp.viewport.width,
            height: fp.viewport.height,
            device_scale_factor: Some(fp.device_scale_factor as f64),
            emulating_mobile: fp.ua_mobile,
            is_landscape: false,
            has_touch: fp.max_touch_points > 0,
        },
        None => Viewport {
            width: 1366,
            height: 768,
            device_scale_factor: Some(1.0),
            emulating_mobile: false,
            is_landscape: true,
            has_touch: false,
        },
    };

    // CLI args focused on stealth + reproducibility:
    //   --disable-blink-features=AutomationControlled removes the
    //     "Chrome is being controlled by automated test software" banner
    //     and the navigator.webdriver default. The JS patch above is the
    //     belt-and-braces backup.
    //   --disable-dev-shm-usage / --no-zygote help on small-RAM hosts
    //     (CI runners, Docker on the VPN compose stack).
    //   --hide-scrollbars + --mute-audio reduce paint cost during
    //     stealth sweeps without affecting detection signals.
    let args: Vec<String> = vec![
        "--disable-blink-features=AutomationControlled".into(),
        "--disable-dev-shm-usage".into(),
        "--disable-features=IsolateOrigins,site-per-process".into(),
        "--no-default-browser-check".into(),
        "--no-first-run".into(),
        "--mute-audio".into(),
        "--hide-scrollbars".into(),
    ];

    let mut builder = BrowserConfig::builder()
        .viewport(viewport)
        .request_timeout(Duration::from_secs(60))
        .launch_timeout(Duration::from_secs(45))
        .args(args)
        .no_sandbox(); // required inside containerised VPN compose stack

    if let Some(path) = &profile.chrome_executable {
        builder = builder.chrome_executable(path);
    }

    if profile.headless {
        // "New" headless mode shares the same surface as a real Chrome
        // window; the legacy headless mode was the one bot.sannysoft
        // detects on sight. `new_headless_mode()` is chromiumoxide's
        // builder shortcut for `HeadlessMode::New` (the type itself is
        // not re-exported).
        builder = builder.new_headless_mode();
    } else {
        builder = builder.with_head();
    }

    builder.build().map_err(|e| {
        StealthError::Permanent(format!("failed to build chromiumoxide BrowserConfig: {e}"))
    })
}

/// A live stealth browser. Holds the chromiumoxide [`Browser`] plus the
/// background event-loop task; both are torn down when the value drops or
/// when [`Self::shutdown`] is called.
pub struct StealthBrowser {
    browser: Browser,
    handler_task: Option<JoinHandle<()>>,
    profile: StealthProfile,
    fingerprint: Option<Fingerprint>,
}

impl StealthBrowser {
    /// Borrow the underlying chromiumoxide browser. Use this to open
    /// pages or send raw CDP commands — the launcher does not wrap every
    /// chromiumoxide call.
    pub fn browser(&self) -> &Browser {
        &self.browser
    }

    /// The profile the browser was launched with.
    pub fn profile(&self) -> &StealthProfile {
        &self.profile
    }

    /// The mobile fingerprint that drove the launch, when applicable.
    pub fn fingerprint(&self) -> Option<&Fingerprint> {
        self.fingerprint.as_ref()
    }

    /// Open a fresh page and apply the stealth bootstrap before the
    /// caller navigates anywhere.
    pub async fn new_page(&self) -> Result<Page> {
        let page = self
            .browser
            .new_page("about:blank")
            .await
            .map_err(|e| StealthError::Transient(format!("new_page: {e}")))?;
        self.apply_to_page(&page).await?;
        Ok(page)
    }

    /// Apply the stealth bootstrap to an existing page. Idempotent —
    /// re-applying is harmless (each patch guards with `Object.defineProperty(... configurable: true)`),
    /// but every duplicate call costs a CDP round-trip.
    pub async fn apply_to_page(&self, page: &Page) -> Result<()> {
        let bootstrap = bootstrap_js(&self.profile);
        if !bootstrap.is_empty() {
            page.evaluate_on_new_document(bootstrap)
                .await
                .map_err(|e| StealthError::Transient(format!("evaluate_on_new_document: {e}")))?;
            debug!(?self.profile.id, "stealth bootstrap installed");
        }

        if let Some(fp) = &self.fingerprint {
            // CDP-level UA override + Sec-CH-UA hints.
            let brands: Vec<_> = fp
                .ua_brands
                .iter()
                .map(
                    |b| chromiumoxide::cdp::browser_protocol::emulation::UserAgentBrandVersion {
                        brand: b.brand.clone(),
                        version: b.version.clone(),
                    },
                )
                .collect();

            // The Sec-CH-UA-Full-Version-List ships the same brands as
            // Sec-CH-UA but tagged with the precise build (e.g. 131.0.6778.86).
            let full_version_list: Vec<_> = fp
                .ua_brands
                .iter()
                .map(
                    |b| chromiumoxide::cdp::browser_protocol::emulation::UserAgentBrandVersion {
                        brand: b.brand.clone(),
                        version: fp.ua_full_version.clone(),
                    },
                )
                .collect();

            let ua_metadata = chromiumoxide::cdp::browser_protocol::emulation::UserAgentMetadata {
                brands: Some(brands),
                full_version_list: Some(full_version_list),
                platform: match fp.device_class {
                    mobile_fp::DeviceClass::Ios => "iOS".to_string(),
                    mobile_fp::DeviceClass::Android => "Android".to_string(),
                },
                platform_version: fp.ua_platform_version.clone(),
                architecture: String::new(), // mobile devices report empty
                model: fp.ua_model.clone(),
                mobile: fp.ua_mobile,
                bitness: Some("64".into()),
                wow64: Some(false),
                form_factors: None,
            };

            let ua_params = SetUserAgentOverrideParams::builder()
                .user_agent(fp.user_agent.clone())
                .accept_language(fp.languages.join(","))
                .platform(fp.platform.clone())
                .user_agent_metadata(ua_metadata)
                .build()
                .map_err(|e| {
                    StealthError::Permanent(format!("build SetUserAgentOverrideParams: {e}"))
                })?;
            page.execute(ua_params)
                .await
                .map_err(|e| StealthError::Transient(format!("setUserAgentOverride: {e}")))?;

            // Extra HTTP headers (Accept-Language fallback for hosts that
            // ignore the CDP override).
            let headers = json!({ "Accept-Language": fp.languages.join(",") });
            let hdr_params = SetExtraHttpHeadersParams::new(
                chromiumoxide::cdp::browser_protocol::network::Headers::new(headers),
            );
            page.execute(hdr_params)
                .await
                .map_err(|e| StealthError::Transient(format!("setExtraHttpHeaders: {e}")))?;
        }

        Ok(())
    }

    /// Gracefully terminate the browser process and the background event
    /// loop. Safe to call multiple times.
    pub async fn shutdown(mut self) -> Result<()> {
        // Best-effort browser close; ignore errors because the process
        // may already have exited.
        if let Err(e) = self.browser.close().await {
            warn!(?e, "browser close returned an error (ignored)");
        }
        if let Err(e) = self.browser.wait().await {
            warn!(?e, "browser wait returned an error (ignored)");
        }
        if let Some(handle) = self.handler_task.take() {
            handle.abort();
        }
        Ok(())
    }
}

impl Drop for StealthBrowser {
    fn drop(&mut self) {
        if let Some(handle) = self.handler_task.take() {
            handle.abort();
        }
    }
}

/// Launch a stealth browser session.
///
/// Performs three async steps:
///
/// 1. Builds a [`BrowserConfig`] from the profile.
/// 2. Spawns the Chromium process via [`Browser::launch`] and the
///    background event-loop task that drives chromiumoxide's stream.
/// 3. Returns the [`StealthBrowser`] handle. The caller must invoke
///    [`StealthBrowser::new_page`] to obtain a page that already has the
///    bootstrap script installed.
pub async fn launch_stealth(profile: StealthProfile) -> Result<StealthBrowser> {
    let config = build_browser_config(&profile)?;
    info!(profile_id = %profile.id, "launching stealth browser");

    let (browser, mut handler) = Browser::launch(config)
        .await
        .map_err(|e| StealthError::Transient(format!("Browser::launch: {e}")))?;

    let handler_task = tokio::spawn(async move {
        // Drive the event loop. Each iteration yields a single CDP event
        // result; we ignore individual errors and let chromiumoxide
        // surface fatal ones via the page-level futures.
        while let Some(event) = handler.next().await {
            if let Err(e) = event {
                debug!(?e, "chromiumoxide event-loop error");
            }
        }
    });

    let fingerprint = profile.browser_profile.preset().map(|p| p.fingerprint());

    Ok(StealthBrowser {
        browser,
        handler_task: Some(handler_task),
        profile,
        fingerprint,
    })
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::BrowserProfile;

    #[test]
    fn bootstrap_off_is_empty() {
        let p = StealthProfile {
            stealth_level: StealthLevel::Off,
            ..StealthProfile::default()
        };
        assert!(bootstrap_js(&p).is_empty());
    }

    #[test]
    fn bootstrap_basic_includes_webdriver_and_chrome_runtime() {
        let p = StealthProfile {
            stealth_level: StealthLevel::Basic,
            ..StealthProfile::default()
        };
        let js = bootstrap_js(&p);
        assert!(js.contains("Navigator.prototype, 'webdriver'"));
        assert!(js.contains("c.runtime ="));
        // Basic must NOT include the mobile fingerprint overrides.
        assert!(!js.contains("UNMASKED_VENDOR"));
        assert!(!js.contains("effectiveType"));
    }

    #[test]
    fn bootstrap_full_mobile_includes_webgl_languages_screen() {
        let p = StealthProfile {
            browser_profile: BrowserProfile::MobileIos,
            stealth_level: StealthLevel::Full,
            ..StealthProfile::default()
        };
        let js = bootstrap_js(&p);
        assert!(js.contains("Navigator.prototype, 'webdriver'"));
        assert!(js.contains("UNMASKED_VENDOR"));
        assert!(js.contains("Apple GPU"));
        assert!(js.contains("ja-JP"));
        // Mobile dimensions
        assert!(js.contains("def('width',       393)"));
    }

    #[test]
    fn bootstrap_full_desktop_skips_mobile_fp_overrides() {
        let p = StealthProfile {
            browser_profile: BrowserProfile::Desktop,
            stealth_level: StealthLevel::Full,
            ..StealthProfile::default()
        };
        let js = bootstrap_js(&p);
        // Static patches present:
        assert!(js.contains("Navigator.prototype, 'webdriver'"));
        assert!(js.contains("c.runtime ="));
        assert!(js.contains("PluginArray"));
        // But no mobile-FP overrides:
        assert!(!js.contains("UNMASKED_VENDOR"));
        assert!(!js.contains("effectiveType"));
        assert!(!js.contains("def('width'"));
    }

    #[test]
    fn build_browser_config_uses_iphone_viewport_for_mobile_ios() {
        let p = StealthProfile {
            browser_profile: BrowserProfile::MobileIos,
            ..StealthProfile::default()
        };
        let cfg = build_browser_config(&p).unwrap();
        // BrowserConfig fields are private; we round-trip through the
        // profile's preset to assert the fingerprint-side input we used.
        let fp = p.browser_profile.preset().unwrap().fingerprint();
        assert_eq!(fp.viewport.width, 393);
        assert_eq!(fp.viewport.height, 852);
        assert!(fp.ua_mobile);
        // Smoke: config builds without error.
        drop(cfg);
    }

    #[test]
    fn build_browser_config_handles_desktop_profile() {
        let p = StealthProfile {
            browser_profile: BrowserProfile::Desktop,
            ..StealthProfile::default()
        };
        let cfg = build_browser_config(&p).unwrap();
        drop(cfg);
    }

    #[test]
    fn build_browser_config_supports_headed_mode() {
        let p = StealthProfile {
            headless: false,
            ..StealthProfile::default()
        };
        let cfg = build_browser_config(&p).unwrap();
        drop(cfg);
    }

    #[test]
    fn bootstrap_full_galaxy_includes_qualcomm_renderer() {
        let p = StealthProfile {
            browser_profile: BrowserProfile::GalaxyUltra,
            stealth_level: StealthLevel::Full,
            ..StealthProfile::default()
        };
        let js = bootstrap_js(&p);
        assert!(js.contains("Adreno (TM) 750"));
        assert!(js.contains("def('width',       384)"));
    }
}
